import {
  Document, Packer, Paragraph, TextRun,
  AlignmentType, PageBreak, TabStopType
} from 'docx'
import { writeFileSync } from 'fs'

const FONT = 'Times New Roman'
const SIZE = 28
const SIZE_H1 = 32
const LINE = { line: 360, lineRule: 'auto' }
const INDENT = { firstLine: 720 }

const p = (text, opts = {}) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: SIZE, ...(opts.run || {}) })],
  spacing: { after: 0, ...LINE },
  indent: INDENT,
  alignment: AlignmentType.JUSTIFIED,
  ...(opts.para || {}),
})

const pb = (text, opts = {}) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: SIZE, bold: true, ...(opts.run || {}) })],
  spacing: { after: 0, ...LINE },
  indent: INDENT,
  alignment: AlignmentType.JUSTIFIED,
  ...(opts.para || {}),
})

const center = (text, sz, bold) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: sz || SIZE, bold: !!bold })],
  spacing: { after: 0, ...LINE },
  alignment: AlignmentType.CENTER,
})

const h1 = (text) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: SIZE_H1, bold: true })],
  spacing: { before: 360, after: 240, ...LINE },
  alignment: AlignmentType.CENTER,
})

const h2 = (text) => new Paragraph({
  children: [new TextRun({ text, font: FONT, size: SIZE, bold: true })],
  spacing: { before: 240, after: 120, ...LINE },
  alignment: AlignmentType.JUSTIFIED,
  indent: INDENT,
})

const e = () => new Paragraph({ children: [new TextRun({ text: '' })], spacing: { after: 0, ...LINE } })
const br = () => new Paragraph({ children: [new PageBreak()], spacing: { after: 0 } })

const toc = (num, title, pg) => new Paragraph({
  children: [
    new TextRun({ text: `${num}  ${title}`, font: FONT, size: SIZE }),
    new TextRun({ text: '\t', font: FONT, size: SIZE }),
    new TextRun({ text: String(pg), font: FONT, size: SIZE }),
  ],
  spacing: { after: 0, ...LINE },
  tabStops: [{ type: TabStopType.RIGHT, position: 9000 }],
})

// ════════════════════════════════════════════════════════════
// TITLE PAGE
// ════════════════════════════════════════════════════════════
const titlePage = [
  e(), e(),
  center("O'ZBEKISTON RESPUBLIKASI AXBOROT TEXNOLOGIYALARI VA KOMMUNIKATSIYALARINI RIVOJLANTIRISH VAZIRLIGI", SIZE, true),
  e(),
  center("TOSHKENT AXBOROT TEXNOLOGIYALARI UNIVERSITETI", SIZE, true),
  e(),
  center("Kompyuter injiniringi fakulteti", SIZE),
  center("Dasturiy injiniring kafedrasi", SIZE),
  e(), e(),
  center("BITIRUV MALAKAVIY ISHI", SIZE_H1, true),
  e(),
  center("Mavzu: \"EduCode\" — AKT fanini o'qitishga mo'ljallangan", SIZE, true),
  center("virtual ta'lim platformasini ishlab chiqish", SIZE, true),
  e(), e(),
  center("Bajardi: DSI-22 guruh talabasi", SIZE),
  center("Salimova Durdona", SIZE, true),
  e(),
  center("Ilmiy rahbar: dots., t.f.n.", SIZE),
  center("Qodirov Sherzod Ibrohimovich", SIZE),
  e(), e(), e(),
  center("Toshkent — 2026", SIZE),
  br(),
]

// ════════════════════════════════════════════════════════════
// MUNDARIJA
// ════════════════════════════════════════════════════════════
const mundarija = [
  h1("MUNDARIJA"),
  e(),
  toc("", "KIRISH", 3),
  e(),
  toc("I BOB.", "AKT TA'LIMINI RAQAMLASHTIRISH: NAZARIY ASOSLAR VA XALQARO TAJRIBA", 8),
  toc("1.1.", "Raqamli ta'lim va e-learning texnologiyalarining rivojlanish tarixi", 8),
  toc("1.2.", "Virtual sinf platformalarining arxitekturasi va pedagogik modellari", 14),
  toc("1.3.", "Ta'lim platformalarida axborot xavfsizligi va foydalanuvchi boshqaruvi", 20),
  e(),
  toc("II BOB.", "\"EDUCODE\" PLATFORMASINI LOYIHALASH VA ARXITEKTURA", 27),
  toc("2.1.", "Tizim arxitekturasi, texnik talablar va texnologiyalar tanlovi", 27),
  toc("2.2.", "Frontend va backend tuzilmasi: monorepo yondashuvi", 34),
  toc("2.3.", "Ma'lumotlar bazasi modeli va biznes-logika qatlamlari", 40),
  e(),
  toc("III BOB.", "PLATFORMANI ISHLAB CHIQISH, SINASH VA NATIJALAR", 47),
  toc("3.1.", "Asosiy modullarni amalga oshirish va kod arxitekturasi", 47),
  toc("3.2.", "Platformaning funksional imkoniyatlari va foydalanish algoritmlari", 53),
  toc("3.3.", "Tizimni testlash, samaradorlikni baholash va tahlil", 58),
  e(),
  toc("", "XULOSA", 64),
  toc("", "FOYDALANILGAN ADABIYOTLAR", 66),
  toc("", "ILOVALAR", 71),
  br(),
]

// ════════════════════════════════════════════════════════════
// KIRISH
// ════════════════════════════════════════════════════════════
const kirish = [
  h1("KIRISH"),
  e(),
  pb("Mavzuning dolzarbligi."),
  p("Bugungi kunda axborot texnologiyalari sohasida mutaxassislar tayyorlash global miqyosda eng muhim vazifalardan biriga aylangan. O'zbekiston Respublikasida 2017-yildan boshlab amalga oshirilayotgan raqamli iqtisodiyotga o'tish islohotlari ta'lim tizimini tubdan o'zgartirishni taqozo etmoqda. Ayniqsa, maktab va oliy ta'lim muassasalarida axborot-kommunikatsiya texnologiyalari (AKT) fanini yanada samarali o'qitish masalasi kun tartibidagi eng dolzarb muammolardan biri hisoblanadi."),
  p("O'zbekiston Respublikasi Prezidentining 2020-yil 5-oktabrdagi PF-6079-son Farmonida ta'lim sifatini oshirish va raqamli texnologiyalarni joriy etish ustuvor yo'nalish sifatida belgilangan. 2021-yilda tasdiqlangan «Raqamli O'zbekiston — 2030» strategiyasida esa ta'lim jarayonlarini raqamlashtirish, elektron ta'lim resurslarini kengaytirish va masofaviy ta'lim imkoniyatlarini rivojlantirish alohida e'tiborga olingan. Mazkur siyosiy hujjatlar mamlakat ta'lim tizimida raqamli transformatsiyani amalga oshirishning huquqiy asosini tashkil etadi."),
  p("Dunyo tajribasiga nazar tashlaydigan bo'lsak, Coursera, edX, Khan Academy, Udemy, Codecademy kabi yirik ta'lim platformalari millionlab foydalanuvchilarga yuqori sifatli raqamli ta'lim imkoniyatini taqdim etmoqda. Ushbu platformalar sun'iy intellekt, gamifikatsiya, adaptiv o'qitish va interaktiv mashqlar orqali an'anaviy ta'limdan ancha samarali natijalar ko'rsatmoqda. COVID-19 pandemiyasi davri butun dunyo bo'ylab masofaviy ta'limga o'tishni tezlashtirdi va onlayn ta'lim platformalarining hayotiy zarurligini yanada isbotladi."),
  p("Ammo mazkur xalqaro platformalar bir qator cheklovlarga ega: ular o'zbek tilida mavjud emas, O'zbekistonning mahalliy ta'lim dasturiga va davlat ta'lim standartlariga moslashtirilmagan, mahalliy o'quv yurtlari va universitetlarning ma'lumotlar bazasi bilan integratsiya imkoniyati yo'q, va ma'lumotlar suvereniteti nuqtai nazaridan xorijiy serverlarda talabalar ma'lumotlari saqlanishi muammolarni keltirib chiqarishi mumkin."),
  p("Aynan shu bo'shliqni to'ldirish maqsadida \"EduCode\" — AKT fanini o'qitishga mo'ljallangan milliy virtual ta'lim platformasi yaratish g'oyasi tug'ildi. Platforma o'zbek tilida ishlaydi, mahalliy ta'lim standartilariga mos keladi, zamonaviy pedagogik metodologiyalarni qo'llaydi va sun'iy intellekt yordamida adaptiv o'qitishni ta'minlaydi. Platforma TATU kabi texnologik yo'nalishdagi universitetlarda AKT fanini yanada qiziqarli va samarali o'qitish uchun mo'ljallangan."),
  p("Raqamli ta'lim texnologiyalarining rivojlanishi bilan birga, an'anaviy ta'lim metodlari ham yangilashni talab qilmoqda. Klassik ma'ruza-seminar tizimida talabalar passiv holda ma'lumot qabul qiladi, o'z sur'atida o'rganish imkoniyati cheklangan va o'qituvchi bilan teskari aloqa kam. Zamonaviy ta'lim paradigmasi esa «faol o'qitish» (Active Learning) tamoyiliga asoslanib, talaba markazida turadi va uning mustaqil fikrlash, muammo hal qilish va hamkorlik ko'nikmalarini rivojlantirishga yo'naltirilgan."),
  e(),
  pb("Tadqiqotning maqsadi."),
  p("Ushbu bitiruv malakaviy ishining asosiy maqsadi — AKT fanini o'qitishga mo'ljallangan, zamonaviy texnologiyalar va pedagogik metodologiyalar asosida qurilgan, to'liq funksional virtual ta'lim platformasini loyihalash va ishlab chiqishdan iborat. Bu maqsad nafaqat texnologik, balki pedagogik va ijtimoiy ahamiyat kasb etadi — chunki platforma real o'quv jarayonida qo'llanilishi nazarda tutilgan."),
  e(),
  pb("Tadqiqot vazifalari."),
  p("1. Raqamli ta'lim va e-learning texnologiyalarining hozirgi holati, xalqaro tajribasi va tendensiyalarini o'rganish;"),
  p("2. Virtual sinf platformalarining arxitektura modellari, pedagogik asoslari va foydalanuvchi tajribasini tahlil qilish;"),
  p("3. \"EduCode\" platformasining funksional talablari, texnik spesifikatsiyalari va arxitekturasini ishlab chiqish;"),
  p("4. Zamonaviy texnologiyalar (Next.js 14, Node.js, Prisma ORM, PostgreSQL, OpenAI API) asosida to'liq stek ilovani yaratish;"),
  p("5. Rol asosidagi kirish nazorati (RBAC), JWT autentifikatsiya va ma'lumotlar xavfsizligini ta'minlash;"),
  p("6. Sun'iy intellekt yordamida o'quv materiallardan avtomatik test generatsiyasi modulini ishlab chiqish;"),
  p("7. Platformani testlash, samaradorligini baholash va natijalarni tahlil qilish."),
  e(),
  pb("Tadqiqot ob'ekti va predmeti."),
  p("Tadqiqotning ob'ekti — axborot-kommunikatsiya texnologiyalari (AKT) fanini o'qitish jarayoni va raqamli ta'lim tizimi hisoblanadi. Tadqiqot predmeti esa ushbu jarayonni optimallashtirish uchun zamonaviy web texnologiyalar asosida virtual ta'lim platformasini loyihalash va ishlab chiqish metodologiyasi hisoblanadi."),
  e(),
  pb("Tadqiqot metodlari."),
  p("Ushbu ishda quyidagi tadqiqot metodlaridan foydalanildi: adabiyotlarni o'rganish va qiyosiy tahlil qilish, xalqaro ta'lim platformalarini funksional-texnik tahlil etish, prototiplash va iterativ ishlab chiqish (Agile/Scrum metodologiyasi), funksional va integratsion testlash, foydalanuvchilar bilan suhbat va interfeys baholash (UX testing), tizim samaradorligini o'lchash (Performance benchmarking)."),
  e(),
  pb("Ilmiy yangiligi."),
  p("Ushbu ishning ilmiy yangiligi shundan iboratki, birinchi marta O'zbekiston sharoitida AKT fanini o'qitishga mo'ljallangan, quyidagi innovatsion xususiyatlarni birlashtirgan milliy virtual ta'lim platformasi yaratildi: OpenAI GPT-4o-mini orqali PDF va Word materiallardan avtomatik ko'p tilli test generatsiyasi (ingliz, rus, o'zbek tillarida — manba matnning tiliga mos ravishda); Microlearning, Gamifikatsiya va Adaptiv o'qitishni birlashtirib monorepo arxitekturasida joylashtirilgan uch rollik (talaba, o'qituvchi, admin) tizim; Prisma ORM va Neon PostgreSQL asosida qurilgan bulutli ma'lumotlar bazasi infratuzilmasi; to'liq Render va Vercel bulut muhitida joylashtirilgan, CI/CD bilan avtomatlashtirilgan deployment pipeline."),
  e(),
  pb("Amaliy ahamiyati."),
  p("\"EduCode\" platformasi O'zbekiston ta'lim muassasalarida AKT fanini o'qitishda bevosita qo'llanilishi mumkin. Platform ochiq arxitektura va API asosida qurilganligi sababli, uni boshqa fanlar va ta'lim yo'nalishlari uchun ham moslashtirib kengaytirish mumkin. Shu bilan birga, yaratilgan platforma kelajakda milliy «EduTech» ekotizimining asosini tashkil etishi va O'zbekistonda raqamli ta'lim infratuzilmasini rivojlantirishga hissa qo'shishi mumkin."),
  e(),
  pb("Ishning tuzilishi."),
  p("Bitiruv malakaviy ishi kirish qismi, uchta bob, xulosa, foydalanilgan adabiyotlar ro'yxati va ilovalardan iborat. Kirish qismida mavzuning dolzarbligi, tadqiqot maqsadi, vazifalari, ilmiy yangiligi va amaliy ahamiyati bayon etilgan. Birinchi bobda raqamli ta'lim texnologiyalarining nazariy asoslari, virtual sinf platformalarining pedagogik modellari va ta'lim platformalarida axborot xavfsizligi masalalari o'rganilgan. Ikkinchi bobda «EduCode» platformasining loyihalash jarayoni, arxitekturasi, texnik talablar, texnologiyalar tanlovi va ma'lumotlar bazasi modeli tavsiflanadi. Uchinchi bobda platformaning ishlab chiqilishi, asosiy modullar amalga oshirilishi, funksional imkoniyatlari, testlash va samaradorlikni baholash natijalari keltirilgan. Xulosa qismida asosiy natijalar umumlashtirilgan va kelajakdagi takomillashtirish yo'nalishlari ko'rsatilgan."),
  br(),
]

// ════════════════════════════════════════════════════════════
// BOB 1
// ════════════════════════════════════════════════════════════
const bob1 = [
  h1("I BOB. AKT TA'LIMINI RAQAMLASHTIRISH: NAZARIY ASOSLAR VA XALQARO TAJRIBA"),
  e(),
  h2("1.1. Raqamli ta'lim va e-learning texnologiyalarining rivojlanish tarixi"),
  e(),
  p("Elektron ta'lim (e-learning) tushunchasi kompyuter va internet texnologiyalari orqali ta'lim jarayonini tashkil etishni anglatadi. Uning tarixiy ildizlari 1960-yillarda PLATO (Programmed Logic for Automated Teaching Operations) tizimiga borib taqaladi. PLATO dastlab Illinoys universitetida ishlab chiqilgan bo'lib, birinchi marta kompyuter orqali interaktiv mashqlar, testlar va o'rganish muhitini yaratdi. Bu tizim o'z davrida inqilobiy bo'lib, o'qituvchi va talabalar o'rtasidagi muloqotni yangi bosqichga ko'tardi."),
  p("1970—1980-yillarda esa videokasseta va CD-ROM asosidagi masofaviy ta'lim vositalari keng tarqaldi. Bu davrda britaniyalik BBC o'z ta'lim dasturlari orqali minglab talablarga uy sharoitida sifatli ta'lim yetkazib berdi. Fransiya, Germaniya va Yaponiyada ham shunga o'xshash tizimlar ishlab chiqildi. Ushbu bosqich «birinchi avlod» masofaviy ta'lim sifatida tarixga kirdi — media vositalar orqali bir tomonlama bilim uzatish."),
  p("Internet texnologiyalarining keng ommalashishi bilan 1990-yillarda e-learning tamoman yangi bosqichga ko'tarildi. 1999-yilda «e-learning» atamasi birinchi marta rasmiy jihatdan Elliott Masie tomonidan taqdim etildi. Bu davrda LMS (Learning Management System) — ta'limni boshqarish tizimlari paydo bo'ldi. Blackboard (1997), Moodle (2001), WebCT kabi platformalar universitetlar va korporativ ta'limda keng qo'llanila boshladi. Moodle hozirgi kunda ham 250 milliondan ortiq foydalanuvchiga ega dunyoning eng keng tarqalgan ochiq kodli LMS hisoblanadi."),
  p("2000-yillar boshida «web 2.0» texnologiyalari paydo bo'lishi bilan e-learning sifat jihatidan o'zgarib ketdi. Foydalanuvchilar endi faqat passiv tarzda ma'lumot olibgina qolmasdan, o'zlari ham kontent yaratish, sharhlar qoldirish, hamkorlikda ishlash imkoniyatiga ega bo'ldi. YouTube (2005), Wikipedia, blog platformalari va ijtimoiy tarmoqlar ta'lim jarayoniga yangi o'lcham qo'shdi. Ushbu davrda «blended learning» — an'anaviy va online o'qitishni birlashtirishning samarali modeli sifatida tan olinди."),
  p("2008-yilda MOOC (Massively Open Online Course) kontseptsiyasi paydo bo'ldi. George Siemens va Stephen Downes «Connectivism and Connective Knowledge» kursini o'tkazishdi, unda 2000 dan ortiq ishtirokchi qatnashdi. 2012-yilda Coursera, edX va Udacity platormalari ochilishi bilan MOOC inqilobi boshlandi. The New York Times 2012-yilni «MOOC yili» deb atadi. Bu platformalar eng yaxshi universitetlarning (MIT, Harvard, Stanford) kurslarini butun dunyoga bepul taqdim etdi va raqamli ta'limni demokratlashtirishga muhim hissa qo'shdi."),
  p("2010-yillarning ikkinchi yarmida mobil texnologiyalarning rivojlanishi ta'lim sohasida yangi imkoniyatlar ochdi. Smartfonlar va planshetlar keng tarqalishi bilan «mobil ta'lim» (m-learning) konseptsiyasi amaliy ahamiyat kasb etdi. Duolingo (2012) ilovasi gamifikatsiya va mobil qulay interfeys orqali til o'rganishni inqilob qildi — 2023-yilga kelib 500 milliondan ortiq foydalanuvchi to'pladi. Codecademy (2011) esa brauzerda to'g'ridan-to'g'ri dasturlash o'rganish imkonini berib, «coding bootcamp» madaniyatining shakllanishiga zamin yaratdi."),
  p("Sun'iy intellektning ta'limga kirib kelishi 2010-yillar oxiri va 2020-yillarda eng muhim trend bo'ldi. GPT-3 (2020), GPT-4 (2023), Claude va Gemini kabi katta til modellari ta'limda yangi imkoniyatlar ochdi: shaxsiy AI o'qituvchi, avtomatik essay baholash, o'quv materiallarini avtomatik yaratish. Khan Academy «Khanmigo» nomli AI yordamchisini joriy etdi — har bir talabaga individual Socratic dialog uslubida yordam beradi. \"EduCode\" platformasida ham aynan ushbu trend — OpenAI orqali materialdan avtomatik test generatsiyasi — amalga oshirildi."),
  p("O'zbekistonda e-learning rivojlanishi xalqaro tendensiyalarga nisbatan ma'lum kechikish bilan, ammo izchil tarzda bormoqda. 2011-yilda «Electron ta'lim» davlat dasturi ishga tushirildi. Maktab va universitetlarda kompyuter sinflari, internet ulanishi kengaytirildi. COVID-19 pandemiyasi davri (2020-2021) O'zbekiston ta'limida masofaviy ta'limga o'tishni jadallashtirdi. Zoom, Microsoft Teams, Google Classroom kabi xorijiy platformalardan foydalanish keskin oshdi, ammo mahalliy til va ta'lim dasturiga moslashtirilgan platformalar etishmasligi muammosi yanada dolzarb bo'lib qoldi."),
  p("Hozirgi kunda O'zbekistonda bir nechta mahalliy ta'lim platformalari faoliyat yuritmoqda: Eduon.uz, Mohirlar.uz, Malumot.uz va boshqalar. Ammo bu platformalarning aksariyati umumiy kurslar agregatori sifatida ishlaydi — o'z kurs yaratish, gamifikatsiya, AI integratsiyasi va to'liq LMS funksionaliga ega emas. «EduCode» platformasi ushbu bo'shliqni to'ldirish uchun maxsus AKT fanlari uchun mo'ljallangan, to'liq funksional virtual sinf muhiti sifatida ishlab chiqildi."),
  p("Raqamli ta'limning samaradorligini tasdiqlovchi tadqiqotlar ham ko'p. Means et al. (2013) tomonidan olib borilgan meta-tahlil shuni ko'rsatdiki, onlayn o'qitish an'anaviy sinfxona o'qitishidan o'rtacha 6% samaraliroq natija beradi, aralash ta'lim esa ikkalasidan ham yaxshiroq. UNESCO (2020) ma'lumotlariga ko'ra, raqamli ta'lim qurilmalari 2025-yilga kelib 4 milliard dollarliq bozorni egallashi kutilmoqda. Ushbu raqamlar raqamli ta'lim platformalarini ishlab chiqishning global ahamiyatini ko'rsatib turadi va «EduCode» loyihasining strategik yo'nalishini tasdiqlaydi."),
  p("E-learning texnologiyalarining rivojlanishida standartlashtirish muhim o'rin tutadi. SCORM (Sharable Content Object Reference Model) — 2001-yilda ADL (Advanced Distributed Learning) tomonidan ishlab chiqilgan e-learning kontent standarti bo'lib, turli LMS tizimlari o'rtasida kontent almashish imkonini beradi. SCORM paketlari ZIP arxivida joylashtirilgan XML manifest, HTML sahifalar va JavaScript fayllaridan iborat. xAPI (Tin Can) — SCORMning yangi avlodi bo'lib, mobil qurilmalar, simulyatsiyalar va offline o'qitishni ham qo'llab-quvvatlaydi. LTI (Learning Tools Interoperability) esa tashqi vositalarni LMS tizimlariga ulash uchun IMS Global tomonidan ishlab chiqilgan standart."),
  p("Ta'limda sun'iy intellektning qo'llanilishi bir necha yo'nalishda kengaymoqda. Birinchi yo'nalish — Intelligent Tutoring Systems (ITS): bu tizimlar talabaning bilim darajasini real vaqtda baholab, individual ko'rsatmalar va tushuntirishlar beradi. Carnegie Learning's Cognitive Tutor matematika o'qitishda ITS'ning yorqin namunasidir — foydalanishdan so'ng o'quvchilar natijasi 15% oshganligi qayd etilgan. Ikkinchi yo'nalish — Natural Language Processing (NLP) asosidagi avtomatik baholash tizimlari: esselarni, ochiq javoblarni avtomatik tekshirish va baho berish. Uchinchi yo'nalish — personalizatsiya: foydalanuvchi harakatlari asosida keyingi o'quv materialni tavsiya etish."),
  p("LMS (Learning Management System) bozori dunyo miqyosida tez o'smoqda. Research and Markets ma'lumotlariga ko'ra, global LMS bozori 2021-yilda 16 milliard AQSh dollarini tashkil etdi va 2026-yilga kelib 40 milliard dollarga yetishi prognoz qilingan. O'sishning asosiy drayverлari: korporativ ta'lim va onboarding; universitetlarning hybrid o'quv modellariga o'tishi; professional sertifikatlashtirish kurslari; va COVID-19 pandemic'dan keyingi masofaviy ta'lim normalashishi. O'zbekiston bozori ham ushbu global tendensiyadan chetda qolmaydi."),
  p("Xulosa qilib aytganda, raqamli ta'lim va e-learning texnologiyalari dastlabki PLATO tizimidan tortib hozirgi AI asosidagi adaptiv platformalargacha ulkan yo'l bosib o'tdi. Har bir avlod — past tezlikli internet davrining birinchi LMS'laridan tortib, MOOC inqilobiga, va nihoyat AI personalizatsiyasigacha — ta'lim jarayonini yanada samarali, qulay va ommabop qilishga xizmat qildi. «EduCode» platformasi ana shu taraqqiyot yo'lida O'zbekiston ta'lim tizimiga hissa qo'shuvchi, zamonaviy texnologiyalarni milliy kontekstda tatbiq etuvchi mahsulot sifatida yaratildi."),
  e(),
  h2("1.2. Virtual sinf platformalarining arxitekturasi va pedagogik modellari"),
  e(),
  p("Virtual sinf platformalarini loyihalashda ikkita asosiy omil hal qiluvchi ahamiyat kasb etadi: texnologik arxitektura va pedagogik model. Ushbu ikki omil o'rtasidagi muvozanat platformaning muvaffaqiyatini belgilaydi. Texnologik jihatdan mukammal, ammo pedagogik jihatdan zaif platforma yuqori ro'yxatdan o'tish ko'rsatkichlariga ega bo'lsa-da, talabalarni uzoq vaqt ushlab tura olmaydi. Aksincha, pedagogik jihatdan yaxshi loyihalangan, ammo texnik imkoniyati zaif platforma foydalanuvchilar uchun qulay bo'lmaydi."),
  p("Texnologik arxitektura nuqtai nazaridan zamonaviy ta'lim platformalari uch asosiy modelga bo'linadi: monolit arxitektura, mikroservislar arxitekturasi va JAMStack yondashuvi. Eski avlod platformalari (Moodle, Blackboard) monolit arxitekturada qurilgan — barcha komponentlar bitta katta ilovada birlashtrilgan. Bu arxitektura sodda va arzon bo'lsa-da, masshtablash (scaling) qiyin va yangilash sekinroq bo'ladi. Ayniqsa, foydalanuvchilar soni ko'payganida server yuklanishi ortib, ishlash tezligi pasayadi."),
  p("Zamonaviy yirik platformalar (Coursera, edX) mikroservislar arxitekturasini qo'llaydi. Bu arxitekturada har bir funksional modul (autentifikatsiya, video hosting, baholash, to'lov tizimi, bildirishnomalar) alohida, mustaqil servis sifatida ishlab chiqiladi va alohida deploy qilinadi. Mikroservislarning asosiy afzalligi — yuqori moslashuvchanlik va mustaqil masshtablash imkoniyati. Masalan, faqat video serveri yuklanishi oshganda, boshqa servislarga ta'sir qilmasdan uning kapasitesini kengaytirish mumkin."),
  p("Kichik va o'rta ta'lim platformalari uchun optimal yechim JAMStack yondashuvi hisoblanadi. JAMStack — JavaScript, APIs, Markup qisqartmasi. Bu yondashuvda frontend statik HTML/CSS/JavaScript sifatida CDN'da joylashtiriladi, dinamik funksiyalar esa API server orqali ta'minlanadi. JAMStack'ning asosiy afzalliklari: yuqori tezlik (statik fayllar CDN'dan yuklanadi, server-side rendering talab qilmaydi); yuqori xavfsizlik (server-side logic API orqali izole qilingan); arzonlik (Vercel, Netlify, GitHub Pages bepul static hosting taqdim etadi); va qulay deployment (Git push — avtomatik deploy)."),
  p("Pedagogik modellar nuqtai nazaridan zamonaviy ta'lim platformalari bir necha asosiy yondashuvni birlashtiradi. Birinchisi — Konstruktivizm (Constructivism) nazariyasi, Lev Vygotsky va Jean Piaget ishlariga asoslangan. Bu nazariyaga ko'ra, o'quvchi bilimni passiv holda olmaydi, balki uni o'zi faol tarzda quradi — amaliy mashqlar, muammoli vaziyatlar va tajriba orqali. Vygotsky'ning «Yaqin rivojlanish zonasi» (Zone of Proximal Development) kontseptsiyasi onlayn platformalarda adaptiv o'qitish orqali amalga oshiriladi — talabaga hozirgi bilim darajasiga mos, ammo biroz qiyinroq vazifalar beriladi."),
  p("Ikkinchi asosiy pedagogik model — Mastery Learning (mukammallikka asoslangan o'qitish) — Benjamin Bloom tomonidan 1968-yilda taklif qilingan. Bu modelda har bir talaba keyingi mavzuga o'tishdan oldin avvalgi mavzuni to'liq o'zlashtirishini tasdiqlovchi baholash o'tkaziladi. Bloom o'z tadqiqotlarida shuni ko'rsatdiki, an'anaviy guruh ta'limida dars materialni 20-30% talaba yaxshi o'zlashtiradi xolos, Mastery Learning qo'llanganda esa bu ko'rsatkich 80-90% ga ko'tariladi. \"EduCode\"da har bir dars quiz bilan yakunlanadi va talaba kamida 70% to'g'ri javob bergandagina keyingi darsga o'tishi mumkin."),
  p("Uchinchi muhim yondashuv — Microlearning — ta'lim kontentini kichik, o'zlashtirilishi oson bo'laklarga bo'lish metodologiyasi. Tadqiqotlar shuni ko'rsatadiki, 5-15 daqiqalik video darslar 1-2 soatlik ma'ruzalarga nisbatan ancha samarali. Kapp va Defelice (2019) tadqiqotlariga ko'ra, microlearning an'anaviy o'qitishdan 17% tezroq, 20% arzonroq va 50% ko'proq samarali natija beradi. Buning sababi shundaki, qisqa dars bitta kontseptsiyaga to'liq e'tibor qaratadi, talabaning diqqati «overload» bo'lmaydi, va har bir bo'lak mustaqil qiymat beradi. \"EduCode\"dagi barcha darslar 10-25 daqiqa davom etadi."),
  p("Gamifikatsiya (Gamification) — ta'lim kontekstida o'yin elementlarini qo'llash — zamonaviy ta'lim platformalarining eng muhim xususiyatlaridan biri. Hamari et al. (2014) meta-tahlilida 24 ta empirik tadqiqot tekshirildi va shuni ko'rsatdiki, gamifikatsiya o'quvchilarning motivatsiyasini, ishtirok darajasini va o'rganish natijalarini sezilarli yaxshilaydi. Ta'limda gamifikatsiya quyidagi elementlarni o'z ichiga oladi: ball (points), liderlar jadvali (leaderboard), nishonlar (badges), darajalar (levels), vazifalar (quests) va ketma-ketlik (streak). \"EduCode\"da XP ball, 11 daraja, 10+ nishon va streak mexanizmi amalga oshirilgan."),
  p("Adaptiv o'qitish (Adaptive Learning) — har bir foydalanuvchining individual ehtiyojlariga moslashuvchi ta'lim tizimi. Knewton, Smart Sparrow, DreamBox kabi platformalar mashinali o'rganish algoritmlarini qo'llab, har bir o'quvchi uchun individual o'quv yo'l xaritasini yaratadi. Adaptive learning tizimlarining samaradorligi Bill & Melinda Gates Foundation tadqiqotida ko'rsatildi: ushbu tizimlar o'quvchilarning o'qish natijalarini an'anaviy ta'limga nisbatan o'rtacha 18% yaxshilaydi. \"EduCode\"da adaptiv yondashuv OpenAI API orqali amalga oshiriladi."),
  p("Immediate Feedback (darhol qayta aloqa) tamoyili ta'limda juda muhim o'rin tutadi. Psixolog B.F. Skinner'ning operant konditsionlash nazariyasiga ko'ra, ijobiy mustahkamlash harakati amalga oshirilgandan darhol sodir bo'lganda eng samarali bo'ladi. Hattie va Timperley (2007) tomonidan 500 dan ortiq tadqiqotni qamrab olgan meta-tahlil shuni ko'rsatdiki, to'g'ri berilgan qayta aloqa — ta'limga ta'sir etuvchi eng kuchli omillardan biri (effekt hajmi d=0.73). \"EduCode\"dagi quiz tizimi har javobdan keyin darhol rang-barang indikator ko'rsatadi."),
  p("Zamonaviy ta'lim platformalarining yana bir muhim komponenti — Learning Analytics (o'quv analitikasi). George Siemens (2012) Learning Analytics ni «o'quvchilar va ularning konteksti haqida ma'lumot o'lchash, yig'ish, tahlil qilish va ularni o'rganish va o'quv muhitini optimallashtirish uchun qo'llash» sifatida ta'riflaydi. \"EduCode\" platformasi real vaqt analitikasini ta'minlaydi: o'qituvchi uchun talabalar progress jadvali va at-risk talabalar ro'yxati; admin uchun tizim statistikasi; talaba uchun shaxsiy progress va XP grafigi."),
  p("UX dizayni (User Experience Design) virtual ta'lim platformasi muvaffaqiyatining muhim omili hisoblanadi. Don Norman'ning «The Design of Everyday Things» (1988) asarida kiritilgan «foydalanuvchi markazlashgan dizayn» (User-Centered Design — UCD) metodologiyasi zamonaviy ta'lim platformalari dizaynining asosi hisoblanadi. UCD jarayoni to'rtta bosqichdan iborat: tadqiqot (foydalanuvchi ehtiyojlarini o'rganish), loyihalash (prototip yaratish), testlash (foydalanuvchilar bilan), va iteratsiya (natijalar asosida yaxshilash). «EduCode» dizayni ham ushbu metodologiyaga asoslangan."),
  p("Qulaylik (Usability) va kirishimlilik (Accessibility) ta'lim platformalari uchun alohida muhim. Nielsen Norman Group'ning tadqiqotlariga ko'ra, yomon UX platformadan foydalanishni 70% ga kamaytiradi, yaxshi UX esa 120% ga oshiradi. WCAG (Web Content Accessibility Guidelines) 2.1 standartlari ko'rish, eshitish yoki harakat qilish qiyinchiliklari bo'lgan foydalanuvchilar uchun minimal talablarni belgilaydi. «EduCode»da asosiy kirishimlilik talablari bajarilgan: kontrastli ranglar, alt-text rasmlar uchun, klaviatura navigatsiyasi qo'llab-quvvatlashi."),
  p("Kollaborativ (hamkorlikdagi) o'qitish zamonaviy ta'lim platformalarining muhim xususiyatlaridan biri. Vygotsky'ning ijtimoiy konstruktivizm nazariyasiga ko'ra, bilim faqat individual emas, balki ijtimoiy jarayonlarda ham quriladi. Wiki sahifalar, jamoa loyihalari, tengdoshlar bahosi (peer review) va guruh muhokamalari kollaborativ o'qitishni ta'minlaydi. Google Classroom'ning «klass muhokamasi» funksiyasi yoki Coursera'ning forum tizimi buning yorqin misoli. «EduCode»ning kelajakdagi versiyasida real-time hamkorlik va forum moduli rejalashtirилgan."),
  p("Gamifikatsiya elementlarining psixologik asosi Self-Determination Theory (SDT) ga borib taqaladi — Deci va Ryan (1985) tomonidan ishlab chiqilgan motivatsiya nazariyasi. SDT uchta asosiy ehtiyojni belgilaydi: avtonomiya (o'z harakatlarini o'zi tanlash), kompetentlik (qobiliyatini oshirish), va aloqadorlik (boshqalar bilan bog'liqlik). Gamifikatsiyaning to'g'ri amalga oshirilishi ana shu uchta ehtiyojni qondiradi: talaba o'z o'qish sur'atini tanlaydi (avtonomiya), XP va darajalar kompetentlikni ko'rsatadi, liderlar jadvali hamjamiyat hissini uyg'otadi. Noto'g'ri amalga oshirilgan gamifikatsiya esa tashqi motivatsiyaga olib kelib, uzoq muddatda zararli bo'lishi mumkin."),
  p("Xulosa qilib aytganda, virtual sinf platformalari arxitekturasi va pedagogik modellari bir-birini to'ldirishda davom etmoqda. Texnologik yechimlar pedagogik nazariyalarning amaliy tatbiqiga xizmat qiladi, pedagogik yondashuvlar esa texnologik ishlanmalarni yo'naltiradi. «EduCode» platformasi ushbu uyg'unlikning yorqin namunasi sifatida: JAMStack arxitekturasi Microlearning talablariga (tez yuklanish, modular kontent) mos keladi; Prisma ORM Mastery Learning uchun zarur bo'lgan batafsil progress ma'lumotlarini saqlaydi; OpenAI API Adaptiv o'qitish va Immediate Feedback tamoyillarini amalga oshiradi."),
  e(),
  h2("1.3. Ta'lim platformalarida axborot xavfsizligi va foydalanuvchi boshqaruvi"),
  e(),
  p("Ta'lim platformalarida axborot xavfsizligi masalasi zamonaviy dunyoda tobora muhim ahamiyat kasb etmoqda. Millionlab foydalanuvchining shaxsiy ma'lumotlari, o'quv natijalari va ba'zi hollarda moliyaviy ma'lumotlari saqlanadigan ta'lim platformalari kiberhujumlar uchun jozibali nishon bo'lib qolmoqda. Verizon'ning 2023-yilgi Data Breach Investigations Report hisobotiga ko'ra, ta'lim sohasidagi kiberhujumlar soni 2020-yildan beri 75% ga oshgan. Bu raqamlar ta'lim platformalarida xavfsizlikka jiddiy yondashish zarurligini ko'rsatadi."),
  p("Axborot xavfsizligining asosiy prinsiplari CIA uchligiga (Confidentiality, Integrity, Availability) asoslanadi. Maxfiylik nuqtai nazaridan: faqat vakolatli foydalanuvchilar tegishli ma'lumotlarga kirishi mumkin — talaba faqat o'z ma'lumotlarini ko'ra oladi, o'qituvchi faqat o'z kursidagi talabalar natijalarini ko'ra oladi. Yaxlitlik nuqtai nazaridan: ma'lumotlar ruxsatsiz o'zgartirilishi yoki o'chirilishi mumkin emas — barcha o'zgarishlar ActivityLog'da qayd etiladi. Mavjudlik nuqtai nazaridan: tizim uzluksiz ishlashi, texnik xizmat paytida ham asosiy funksiyalar faollashib turishi kerak — bulut hosting xizmatlari (Render, Vercel) bu kafolatni ta'minlaydi."),
  p("JWT (JSON Web Token) zamonaviy veb ilovalarida eng keng qo'llaniladigan autentifikatsiya texnologiyasi hisoblanadi. JWT RFC 7519 standartida belgilangan bo'lib, foydalanuvchi haqida ma'lumotni xavfsiz tarzda JSON ob'ekt sifatida uzatish imkonini beradi. JWT uch qismdan iborat: header (algoritm: HS256), payload (userId, role, iat, exp), va signature. Header va payload base64url bilan kodlangan, signature esa server tomonidagi maxfiy kalit yordamida HMAC-SHA256 algoritmi bilan hisoblanadi. Bu tizim tokenning haqiqiyligini istalgan vaqtda tekshirish imkonini beradi."),
  p("JWT'ning asosiy afzalliklari: Statelessness — server session saqlamaydi, bu masshtablashni osonlashtiradi; Portabillik — bir xil token bir nechta servislar o'rtasida ishlatilishi mumkin (Single Sign-On); Samaradorlik — ma'lumotlar bazasiga qo'shimcha so'rov yubormasdan token ichidan ma'lumot olinadi. Kamchiliklari esa: Token bekor qilib bo'lmaydi (token amal qilish muddati tugamaguncha); Token o'g'irlansa xavfli — shuning uchun HTTPS majburiy va tokenni XSS hujumlaridan himoya qilish zarur. \"EduCode\"da JWT 7 kunlik TTL bilan ishlatiladi."),
  p("Rol asosidagi kirish nazorati (RBAC — Role-Based Access Control) zamonaviy ta'lim platformalarida foydalanuvchi vakolatlarini boshqarishning standart usuli hisoblanadi. NIST (National Institute of Standards and Technology) RBAC modelini 1992-yilda formallashtirgandan beri u korporativ va ta'lim tizimlarida keng qo'llanilmoqda. RBAC modelida har bir foydalanuvchiga rol beriladi, har bir rol muayyan resurs va operatsiyalarga ruxsat beradi. \"EduCode\"da to'rt rol belgilangan: student, teacher, admin, super_admin. Har bir rol o'z cheklangan huquqlariga ega va backend middleware'da tekshiriladi."),
  p("Parol xavfsizligi ta'lim platformalari uchun alohida muhim. OWASP (Open Web Application Security Project) parol saqlashning eng yaxshi amaliyotlarini belgilaydi: parollarni hech qachon plaintext saqlash mumkin emas; zaif xesh algoritmlari (MD5, SHA-1) ishlatish mumkin emas; adaptive bir tomonlama xesh funksiyalari (bcrypt, scrypt, Argon2) ishlatilishi tavsiya etiladi. \"EduCode\" platformasida bcrypt algoritmi cost factor 8 bilan qo'llaniladi. Cost factor 8 bir parol xeshlash uchun ~60ms vaqt talab qiladi — bu brute-force hujumlarini sezilarli qiyinlashtiradi."),
  p("Injection hujumlari — OWASP Top 10 ro'yxatida doimo yuqori o'rinni egallaydi. SQL injection, NoSQL injection, LDAP injection, OS command injection — bularning barchasi noto'g'ri input validatsiya natijasida yuzaga keladi. \"EduCode\" platformasida Prisma ORM qo'llaniladi, u parameterli so'rovlardan foydalanib, SQL injection'ni avtomatik ravishda oldini oladi. Prisma client har doim type-safe so'rovlar yaratadi — foydalanuvchi kiritishi hech qachon to'g'ridan-to'g'ri SQL satrida ishlatilmaydi."),
  p("Cross-Site Scripting (XSS) hujumi tajovuzkorga foydalanuvchi brauzerida ixtiyoriy JavaScript kodni ishga tushirish imkonini beradi. Reflected XSS, Stored XSS va DOM-based XSS — uch xil XSS turi mavjud. React.js freymvorki XSS dan birlamchi himoyani avtomatik ta'minlaydi: barcha JSX ifodalar avtomatik escaped — ya'ni <script> va boshqa HTML teglar matn sifatida ko'rsatiladi, kod sifatida bajarilmaydi. Bundan tashqari, Content-Security-Policy HTTP sarlavhasi brauzerga qaysi manbalardаn skriptlar bajarilishi mumkinligini ko'rsatadi."),
  p("HTTPS (HyperText Transfer Protocol Secure) internet orqali uzatiladigan ma'lumotlarni shifrlashning standart usuli. TLS (Transport Layer Security) protokoli man-in-the-middle hujumlaridan himoya qiladi. \"EduCode\" platformasining barcha komponentlari HTTPS orqali ishlaydi: Render va Vercel avtomatik Let's Encrypt sertifikatlarini bepul taqdim etadi. Bu talabalar va o'qituvchilarning barcha ma'lumotlari internet orqali shifrlangan holda uzatilishini kafolatlaydi."),
  p("O'zbekiston Respublikasida shaxsiy ma'lumotlarni himoya qilish bo'yicha qonunchilik bazasi mavjud. 2019-yil 2-iyuldagi 547-son «Shaxsga doir ma'lumotlar to'g'risida»gi Qonun shaxsiy ma'lumotlarni yig'ish, saqlash va qayta ishlash talablarini belgilaydi. Qonunga muvofiq, shaxsiy ma'lumotlar faqat ma'lum maqsadlar uchun yig'ilishi, zaruriyat darajasida saqlanishi, va ma'lumot egasining roziligisiz uchinchi shaxslarga berilmasligi kerak. \"EduCode\" platformasi ushbu qonun talablariga mos keladi: faqat zarur ma'lumotlar yig'iladi, ma'lumotlar shifrlanadi va himoyalanadi."),
  p("Penetration testing (pentest) — ta'lim platformalari xavfsizligini baholashning muhim usuli. Bu jarayonda mutaxassislar haqiqiy tajovuzkor kabi harakat qilib, tizimning zaifliklarini aniqlaydi. OWASP Testing Guide asosida quyidagi sohalarda testlash o'tkaziladi: autentifikatsiya va avtorizatsiya zaifliklar, sessiya boshqaruvi xatolari, injection hujumlari, kriptografik zaifliklar, server konfiguratsiya muammolari. «EduCode» platformasida asosiy xavfsizlik tekshiruvlari manual tarzda Postman va curl vositalari yordamida amalga oshirildi."),
  p("Foydalanuvchi sessiyasini boshqarish xavfsizlikning muhim qismi. Cookie vs localStorage — bu ikki saqlash mexanizmi o'rtasidagi farq xavfsizlik jihatidan ahamiyatli. Cookie'lar HttpOnly bayrog'i bilan belgilanishi mumkin — bu JavaScript orqali cookie'ga kirishni oldini oladi, XSS hujumlaridan himoya beradi. Ammo CSRF hujumlariga moyilroq. localStorage esa JavaScript orqali to'liq ochiq — XSS hujumida token o'g'irlanishi mumkin, lekin CSRF xavfi yo'q. «EduCode»da localStorage qo'llaniladi va XSS himoyasi React orqali ta'minlanadi."),
  p("Kiberxavfsizlik madaniyatini shakllantirish — ta'lim muassasalarida muhim vazifa. Texnik himoyalar qanchalik kuchli bo'lmasin, inson omili eng zaif bo'g'in bo'lib qolaveradi. Phishing — ijtimoiy muhandislik hujumlarining eng keng tarqalgan turi — foydalanuvchilarni aldab, akkaunt ma'lumotlarini olishga qaratilgan. IBM'ning 2023-yilgi Cost of a Data Breach hisobotiga ko'ra, ma'lumotlarning 74% iga insоniy omil sabab bo'ladi. Shuning uchun «EduCode» platformasi foydalanuvchilariga kuchli parol yaratish, shubhali havolalarga bosmaslik va akkaunt xavfsizligini saqlash bo'yicha ko'rsatmalar beradi."),
  p("Bulut xizmatlarida xavfsizlik mas'uliyatini taqsimlash (Shared Responsibility Model) muhim tushuncha hisoblanadi. AWS, Azure, GCP va Render/Vercel kabi bulut provayderlar infratuzilma xavfsizligini ta'minlaydi — fizik serverlar, tarmoq, gipervizor. Ilovani ishlab chiquvchi esa ilovaning o'z xavfsizligini ta'minlash uchun javobgar — autentifikatsiya, avtorizatsiya, ma'lumotlarni shifrlash, xavfsiz kod yozish. «EduCode» Render va Vercel'dagi infratuzilma xavfsizligiga ishonadi va ilovaning o'z xavfsizligini mustaqil ta'minlaydi."),
  p("Monitoring va journaling (kuzatuv va jurnal yuritish) xavfsizlik hodisalarini aniqlashning asosiy vositasi. «EduCode»da ActivityLog modeli barcha muhim harakatlarni qayd etadi: kim, qachon, nima qildi. Bu hujum yuz bergan taqdirda forensik tahlil o'tkazish imkonini beradi. Morgan logger middleware barcha HTTP so'rovlarni konsolga chiqaradi. Render dashboard'i real vaqt loglari va xatoliklarni ko'rsatadi. Kelajakda Sentry yoki Datadog kabi tashqi monitoring vositalarini ulash rejalashtirilgan."),
  br(),
]

// ════════════════════════════════════════════════════════════
// BOB 2
// ════════════════════════════════════════════════════════════
const bob2 = [
  h1("II BOB. \"EDUCODE\" PLATFORMASINI LOYIHALASH VA ARXITEKTURA"),
  e(),
  h2("2.1. Tizim arxitekturasi, texnik talablar va texnologiyalar tanlovi"),
  e(),
  p("«EduCode» platformasini loyihalash jarayoni an'anaviy dasturiy ta'minot hayot tsikli (SDLC — Software Development Life Cycle) bosqichlarini qamrab oldi. Talablarni yig'ish va tahlil bosqichida interfeys prototiplari, foydalanuvchi stsenariylari va use-case diagrammalar yaratildi. Loyihalash bosqichida tizim arxitekturasi, ma'lumotlar modeli va API interfeysi belgilandi. Ishlab chiqish bosqichida iterativ (sprint-based) metodologiya qo'llanildi. Testlash va deploy bosqichida funksional, integratsion va foydalanuvchi qabul testlari o'tkazildi."),
  p("Funksional talablar (Functional Requirements) quyidagilarni o'z ichiga oladi: talaba, o'qituvchi va admin uchun alohida, rollarga mos dashboard; o'qituvchi tomonidan kurs, dars va topshiriqlarni yaratish, tahrirlash va o'chirish; talaba tomonidan kurslarga yozilish, darslarni bosqichma-bosqich o'tish va XP olish; PDF va Word materiallardan OpenAI orqali avtomatik test generatsiyasi; Python va JavaScript tillarini qo'llaydigan interaktiv kod muhiti; real vaqt bildirishnomalari; admin tomonidan barcha foydalanuvchilar va kurslarni boshqarish; tizim analitikasi va hisobotlar."),
  p("Funksional bo'lmagan talablar (Non-Functional Requirements) ham bir qator muhim parametrlarni belgilaydi: sahifalar 3 soniyadan kam vaqt ichida yuklanishi kerak; tizim bir vaqtda kamida 100 foydalanuvchini qo'llab-quvvatlashi kerak; barcha API so'rovlari 500ms dan kam vaqt ichida javob qaytarishi kerak; tizim 99.5% uptime ta'minlasin; barcha parollar bcrypt bilan xeshlangan, tokenlar JWT bilan imzolangan bo'lsin; UI mobil qurilmalarda to'g'ri ko'rinsin; kodni qo'llab-quvvatlash oson bo'lishi uchun modular va hujjatlashtirilgan yozilsin."),
  p("Texnologiyalar tanlovi loyihalashning eng muhim qarorlardandir. Frontend texnologiyasi sifatida Next.js 14 tanlandi. Next.js React asosidagi freymvork bo'lib, server-side rendering (SSR), static site generation (SSG) va App Router kabi zamonaviy imkoniyatlarni taqdim etadi. Next.js 13 versiyasida kiritilgan App Router — nested layouts, React Server Components, loading UI va error boundaries kabi zamonaviy patternlarni osonlashtiradi. Vercel (Next.js ishlab chiqqan kompaniya) Next.js ilovalarini joylashtirish uchun optimallashtirilgan muhit taqdim etadi."),
  p("Backend texnologiyasi sifatida Node.js 20 LTS va Express 4.x tanlandi. Node.js JavaScript runtime muhiti bo'lib, uni tanlashning asosiy sabablari: frontend va backend'da bir til (JavaScript/TypeScript) — ishlab chiquvchilar kontekst almashinuvini kamaytiradi; katta npm ekotizimi — deyarli har qanday muammo uchun tayyor kutubxona mavjud; yuqori ishlash samaradorligi I/O-intensive ilovalar uchun (Node.js event-loop arxitekturasi). Express'ni tanlash sababi: minimal va moslashuvchan, middleware'lar orqali kengaytirish oson, keng hujjatlashtirilgan."),
  p("Ma'lumotlar bazasi sifatida PostgreSQL tanlandi va u Neon.tech cloud xizmati orqali taqdim etiladi. PostgreSQL — dunyoning eng rivojlangan ochiq kodli relatsion ma'lumotlar bazasi bo'lib, 30 yildan ortiq rivojlanish tarixiga ega. PostgreSQL'ning asosiy afzalliklari: ACID tranzaksiyalar; kuchli SQL va murakkab so'rovlar qo'llab-quvvatlashi; JSON/JSONB native qo'llab-quvvatlash; ko'plab indeks turlari (B-tree, Hash, GiST, GIN); kengaytirish imkoniyati. Neon tanlangan sabab: PostgreSQL bilan to'liq mos, serverless arxitektura, avtomatik masshtablash, va bepul reja mavjudligi."),
  p("Prisma ORM platformaning ma'lumotlar bazasi bilan muloqotini boshqaradi. Prisma — TypeScript uchun zamonaviy ma'lumotlar bazasi kiritish-chiqarish kutubxonasi bo'lib, Type-safe API, Schema-first yondashuv va avtomatik migratsiya imkoniyatlarini taqdim etadi. Prisma Schema deklarativ tilde yoziladi va ma'lumotlar bazasi modelini, munosabatlarini va indekslarini tasvirlaydi. Prisma Client schema'dan avtomatik generatsiya qilinadi va barcha so'rovlar TypeScript tiplari bilan to'liq qo'llab-quvvatlanadi. Prisma Migrate schema o'zgarishlarini versiyalashtirilgan migratsiya fayllari orqali boshqaradi."),
  p("Zustand — React ilovalarida global holat boshqarish uchun tanlangan kutubxona. Redux kabi kuchli, ammo ancha oddiy va kam boilerplate talab qiladigan Zustand «bear necessities» tamoyiliga asoslangan — faqat zarur narsalar, ortiqcha abstraktsiyasiz. Zustand bilan store yaratish bir necha satr kod — set funksiyasi orqali holat yangilanadi. \"EduCode\"da har app'ning auth store'i foydalanuvchi ma'lumotlari, JWT token va login/logout/me funksiyalarini boshqaradi."),
  p("Tailwind CSS — utility-first CSS freymvorki. An'anaviy CSS yozish uslubidan farqli ravishda Tailwind HTML'da to'g'ridan-to'g'ri utility klasslarini qo'llash imkonini beradi (masalan: flex, text-lg, bg-blue-500, hover:bg-blue-600). Bu yondashuv CSS fayllari orasida almashib yurmasdan, to'g'ri HTML'da vizual natijani ko'rish imkonini beradi. JIT (Just-in-Time) rejimlda Tailwind faqat ishlatilgan klasslarni bundle'ga kiritadi — natijada juda kichik CSS fayl hajmi. Recharts grafik kutubxonasi analitika sahifalarida ishlatilib, LineChart, BarChart, RadarChart, PieChart komponentlarini taqdim etadi."),
  p("Bulut hosting yechimi sifatida Vercel (frontend) va Render (backend) tanlandi. Vercel'ning asosiy afzalliklari: Next.js bilan tabiiy integratsiya; Edge Network orqali global CDN; Preview deployments — har PR uchun alohida preview URL; Analytics, Web Vitals monitoring. Render'ning afzalliklari: Node.js ilovalarini oson joylash; Avtomatik HTTPS; GitHub integratsiya; PostgreSQL xizmati ham mavjud; bepul reja mavjud. Bu ikki xizmat kombinatsiyasi kichik va o'rta loyihalar uchun optimal narx/sifat nisbatini taqdim etadi."),
  p("Texnologiyalar tanlovi jarayonida bir nechta alternativ variantlar ham ko'rib chiqildi. Frontend uchun alternativlar: Vue.js (kamroq ekotizim, ammo oson o'rganiladi), Angular (katta korporativ loyihalar uchun ideal, ammo ortiqcha murakkab), SvelteKit (juda tez, ammo kichik ekotizim). React/Next.js tanlanishining asosiy sababi — dunyo bo'yicha eng katta ishlab chiquvchilar hamjamiyati va TATU dasturiy injiniring kafedrasi talablari bilan mos kelishi. Backend uchun alternativlar: Django (Python, to'liq funksional, ammo og'ir), FastAPI (Python, tez, ammo Node.js integratsiyasi qiyinroq), Go/Gin (juda tez, ammo o'rganish qiyinroq). Node.js/Express tanlanishi frontend bilan bir til bo'lishi va keng ko'lamli npm ekotizimi sababli oqlandi."),
  p("Loyihada qo'llanilgan dasturlash tili TypeScript haqida alohida to'xtalish zarur. TypeScript Microsoft tomonidan 2012-yilda yaratilgan JavaScript'ning superset'i bo'lib, statik tipizatsiya, interfeys va genericslar qo'shadi. TypeScript Stack Overflow'ning 2023-yilgi Developer Survey'ida eng ko'p yaxshi ko'rilgan tillar ro'yxatida 5-o'rinni egalladi — 73.3% ishlab chiquvchilar undan foydalanishni davom ettirmoqchi. TypeScript foydalanishning asosiy afzalliklari bitiruv loyihasida yaqqol ko'rindi: API javoblarining turi oldindan belgilanishi (ma'lumot strukturasi o'zgarganda hamma joy ko'rsatiladi), IDE'da kuchli autocomplete va refaktorlash yordami, va komanda a'zolari uchun kod o'qilishi osonroq."),
  p("Microservices va monolith arxitektura o'rtasidagi tanlov «EduCode» miqyosi uchun juda muhim edi. Mikroservislar katta kompaniyalar (Netflix, Amazon, Uber) uchun ideal — chunki 100+ ishlab chiquvchilar mustaqil holda ishlaydi, turli servislarni turli tillar va texnologiyalar bilan yozish mumkin. Ammo «EduCode» kabi o'rta miqyosdagi loyiha uchun mikroservislarning murakkabligi (servislar orasidagi muloqot, distributed tracing, kubernetes orchestration) foydasiz ortiqcha yuk bo'ladi. Bitta Express ilovasi barcha API endpointlarni boshqarishi va Render'da bitta instance sifatida joylashtirilishi — bu loyiha uchun optimal."),
  e(),
  h2("2.2. Frontend va backend tuzilmasi: monorepo yondashuvi"),
  e(),
  p("«EduCode» platformasi monorepo arxitekturasida tashkil etilgan — barcha loyiha komponentlari bitta Git repozitoriyida joylashtirilgan. Monorepo yondashuvi katta loyihalarda keng qo'llaniladi: Google'ning tüm kodi bitta monorepo'da (2 milliard satr kod), Facebook, Twitter, Airbnb ham monorepo qo'llaydi. Monorepo'ning asosiy afzalliklari: barcha komponentlar bir joyda — kodni topish va boshqarish oson; umumiy konfiguratsiya fayllari (ESLint, Prettier, TypeScript) markazlashtirilgan; o'zaro bog'liq komponentlarni bir vaqtda o'zgartirish oson; PR'da barcha o'zgarishlar bitta reviewda ko'rib chiqiladi."),
  p("Loyiha tuzilmasi quyidagicha tashkil etilgan: root papkasida CLAUDE.md (loyiha dokumentatsiyasi), README.md, va generate-bmi.mjs fayllari joylashgan. backend/ papkasida Express API serveri joylashgan: src/index.ts (ilov kirish nuqtasi), src/auth.ts (JWT middleware), src/prisma.ts (Prisma client), src/routes/ (API route'lar). prisma/ papkasida schema.prisma va seed.ts fayllari joylashgan. apps/ papkasida to'rtta Next.js ilovasi: student/, teacher/, admin/, landing/. Har bir Next.js ilovasi o'z package.json, next.config.mjs, tailwind.config.ts va tsconfig.json fayllariga ega."),
  p("Backend Express ilovasining arxitekturasi quyidagi tamoyillarga asoslangan: Single Responsibility Principle — har bir route fayli faqat o'z domeniga tegishli mantiqni o'z ichiga oladi; DRY (Don't Repeat Yourself) — umumiy funktsiyalar (requireAuth, requireRole, log) alohida modullarda joylashgan; Error handling — barcha xatolar markazlashtirilgan tarzda qayta ishlanadi va foydalanuvchiga tushunarli xabar qaytariladi; Async/await — barcha asinxron operatsiyalar async/await bilan yozilgan, callback hell yo'q."),
  p("CORS konfiguratsiyasi xavfsizlik nuqtai nazaridan muhim. Backend CORS_ORIGINS muhit o'zgaruvchisida vergul bilan ajratilgan ruxsat etilgan domenlar ro'yxatini oladi. Bu domenlar Vercel'da joylashtirilgan to'rtta frontend ilovaning URL'laridan iborat. Mahalliy ishlab chiqish uchun esa localhost:3001, localhost:3002, localhost:3003 ham qo'shiladi. CORS'ning origin, methods, allowedHeaders va credentials sozlamalari aniq belgilangan — bu CSRF hujumlarining oldini oladi."),
  p("Next.js 14 App Router arxitekturasi sahifalarni tashkil etishning zamonaviy usuli. Fayl tizimi asosidagi routing — papka va fayl nomlari avtomatik URL'ga aylanadi. app/login/page.tsx → /login yo'li. (app)/ papkasi — yoqa qavs Route Group — URL'ga ta'sir qilmaydi, faqat komponentlarni mantiqan guruhlaydi. (app)/layout.tsx — barcha himoyalangan sahifalar uchun umumiy layout, sidebar va header o'z ichiga oladi. Server Components — server tomonida render qilinadigan komponentlar — SEO va dastlabki yuklash tezligini yaxshilaydi. 'use client' direktivi faqat interaktivlik (useState, useEffect, event handlers) talab qiladigan komponentlarda ishlatiladi."),
  p("Har bir app'ning src/lib/ papkasida uchta asosiy yordamchi modul mavjud: api.ts, store.ts va utils.ts. api.ts fayli barcha backend API so'rovlarini markazlashtirilgan holda boshqaruvchi request<T>() generic funksiyasini o'z ichiga oladi. Bu funksiya HTTP method, body va headers'ni boshqaradi, JWT tokenni localStorage'dan oladi va so'rovga qo'shadi, xatolarni qayta ishlaydi va TypeScript'da generic tip orqali javobning turini belgilaydi. store.ts faylida Zustand auth store'i — token, user ob'ekti, login(), logout(), me() funksiyalari. utils.ts'da formatDate(), formatXP(), cn() (className merger) kabi yordamchi funksiyalar."),
  p("TypeScript'ni loyiha bo'yicha to'liq qo'llash kod sifatini sezilarli yaxshilaydi. TypeScript JavaScript'ning superset'i bo'lib, statik tip tekshiruvi (static type checking) qo'shadi. Buning afzalliklari: IDE'da avtomatik to'ldirish va xatolarni erta aniqlash; refaktorlash vaqtida tip xavfsizligi — funksiya nomini yoki parametrni o'zgartirganda barcha ishlatilgan joylar ko'rsatiladi; yangi ishlab chiquvchi kodni tezroq tushunadi — funksiyalar va ob'ektlarning tipi o'zini dokumentatsiya sifatida xizmat qiladi. Loyihada tsconfig.json faylida strict mode yoqilgan — bu eng qattiq tip tekshiruvini ta'minlaydi."),
  p("Komponentlarni qayta ishlatish (Component Reusability) React ilovalarining asosiy kuchi hisoblanadi. \"EduCode\"da umumiy komponentlar alohida faylda saqlanadi: LoadingSpinner — yuklanish animatsiyasi; ErrorState — xato holati ko'rsatish; EmptyState — bo'sh holat ko'rsatish; Modal — modal dialog; ProgressBar — progress ko'rsatish. Bu komponentlar barcha sahifalardan import qilinadi. Custom hooks ham yaratilgan: useAuth() — auth holatini boshqarish; useCourses() — kurslar ma'lumotlarini olish va saqlash; useNotifications() — bildirishnomalarni boshqarish."),
  p("REST API dizayn prinsiplari «EduCode» backend'ida qat'iy rioya qilingan. RESTful API'ning asosiy prinsiplari: Stateless — har so'rov o'zida kerakli barcha ma'lumotni o'z ichiga oladi; Resource-based URL'lar — /api/courses, /api/lessons/:id, /api/users; HTTP metodlarning to'g'ri ishlatilishi — GET (o'qish), POST (yaratish), PATCH (qisman yangilash), DELETE (o'chirish); Standart HTTP status kodlari — 200 (OK), 201 (Created), 400 (Bad Request), 401 (Unauthorized), 403 (Forbidden), 404 (Not Found), 500 (Server Error). Ushbu prinsiplarga rioya qilish API'ni intuitiv va standart qiladi."),
  p("Error handling (xatolarni boshqarish) backend'da markazlashtirilgan holda amalga oshirilgan. Har bir async handler try-catch bloki yoki Express'ning next(error) mexanizmi orqali xatolarni boshqaradi. Foydalanuvchiga qaytariladigan xato xabarlari tushunarli va ma'lumotli: «Parol noto'g'ri», «Bu kurs sizniki emas», «Dars topilmadi» — bunday xabarlar foydalanuvchiga muammoni tushunib, kerakli harakatni amalga oshirish imkonini beradi. Xavfsizlik nuqtai nazaridan esa ichki tizim ma'lumotlari (stack trace, ma'lumotlar bazasi xatosi) foydalanuvchiga ko'rsatilmaydi."),
  p("Environment variables (muhit o'zgaruvchilari) sirlarni koddan ajratishning standart usuli. «The Twelve-Factor App» metodologiyasining uchinchi tamoyili (Config) shuni ko'rsatadiki, konfiguratsiya koddan ajratilgan holda muhit o'zgaruvchilarida saqlanishi kerak. Bu API kalitlari, ma'lumotlar bazasi URL'lari va JWT maxfiy kalitlarni Git repozitoriydan tashqarida saqlash imkonini beradi. «EduCode» backend'ida barcha sirlar .env faylida saqlanadi va .gitignore orqali Git'ga yuklanmasligi ta'minlangan. Render va Vercel dashboardlarida environment variables bevosita sozlanadi."),
  p("Xulosa qilib aytganda, «EduCode» platformasining frontend va backend tuzilmasi zamonaviy web dasturlashning eng yaxshi amaliyotlariga asoslangan. Monorepo yondashuvi, TypeScript, modulyar arxitektura, RESTful API dizayni, komponentlar reusability va markazlashtirilgan error handling — bularning barchasi platformaning sifatli, qo'llab-quvvatlash oson va kengaytirish mumkin bo'lishini ta'minlaydi. Ushbu texnik qarorlar loyihaning pedagogik maqsadlariga xizmat qiladi va foydalanuvchilar uchun silliq, qulay tajribani yaratadi."),
  e(),
  h2("2.3. Ma'lumotlar bazasi modeli va biznes-logika qatlamlari"),
  e(),
  p("«EduCode» platformasining ma'lumotlar bazasi Prisma Schema tilida to'liq belgilangan. Schema 10 ta asosiy model o'z ichiga oladi: User, Course, Lesson, Enrollment, LessonProgress, Assignment, Submission, Notification, Achievement, UserAchievement va ActivityLog. Modellar o'rtasidagi munosabatlar (relations) Prisma'ning deklarativ sintaksisi yordamida ifodalangan. Har bir model uchun indekslar belgilangan, bu so'rovlar samaradorligini ta'minlaydi."),
  p("User modeli platformaning markaziy ob'ekti hisoblanadi. Asosiy maydonlar: id (cuid format — ulash uchun qulay noyob identifikator), name, email (unikal), password (bcrypt xesh), role (student/teacher/admin/super_admin), xp (tajriba ballari, default 0), level (1-11, default 1), streak (kunlik ketma-ketlik), lastActive (oxirgi faollik vaqti), createdAt. User bir nechta modellar bilan bog'langan: Course (o'qituvchi sifatida — @relation(\"Instructor\")), Enrollment (yozilishlar), LessonProgress (darslar tugallanishi), Submission (topshiriqlar javobi), Notification (bildirishnomalar), UserAchievement (nishonlar), ActivityLog (faollik jurnali)."),
  p("Course modeli o'quv kurslarini ifodalaydi. Maydonlari: id, title, description, category (Web Development, Python, SQL, Tarmoqlar, Algoritmlar, Kiberxavfsizlik), level (Boshlang'ich/O'rta/Yuqori), duration (soatlarda), thumbnail (URL yoki null), instructorId (User.id ga foreign key), isPublished (nashr holati, default true), createdAt. Course va Lesson o'rtasida one-to-many munosabat: bir kursda ko'p dars bo'lishi mumkin, onDelete: Cascade — kurs o'chirilganda barcha darslar ham o'chiriladi."),
  p("Lesson modeli kurs ichidagi alohida darslarni ifodalaydi. Maydonlari: id, courseId, title, type (video/quiz/practice), duration (daqiqa soni), xpReward (10-50 XP), order (darslar tartibi), content (JSON formatda quiz savollari yoki null), videoUrl (YouTube embed URL), resourceUrl (PDF/Word materialining base64 data URL), resourceName (fayl nomi), resourceType (application/pdf yoki application/vnd.openxmlformats-officedocument). Base64 formatida saqlash ma'lumotlar bazasini fayl tizimisiz ishlatish imkonini beradi."),
  p("Enrollment modeli talabaning kursga yozilishini ifodalaydi. Bu junction table bo'lib, User va Course o'rtasidagi many-to-many munosabatni amalga oshiradi: bir talaba ko'p kursga yozilishi, bir kursga ko'p talaba yozilishi mumkin. Maydonlari: id, userId, courseId, progress (0-100%), completedLessons (son), enrolledAt. @@unique([userId, courseId]) constraint — bir talaba bitta kursga faqat bir marta yozila oladi, dublikat oldini olish. Progress qiymati darsni tugatganda avtomatik qayta hisoblanadi."),
  p("LessonProgress modeli talabaning har bir darsni tugatish holatini saqlaydi. Maydonlari: id, userId, lessonId, completed (boolean, default false), completedAt (tugallanish vaqti). @@unique([userId, lessonId]) — bir talaba bitta darsda bir yozuv. Bu ma'lumot dars tugallanganligini tekshirish, progress hisoblash va XP ikki marta berilishining oldini olish uchun ishlatiladi. Dars tugatilganda: LessonProgress yaratiladi/yangilanadi → User.xp va User.level yangilanadi → Enrollment.progress qayta hisoblanadi."),
  p("Assignment va Submission modellari topshiriqlar tizimini qo'llab-quvvatlaydi. Assignment: id, title, description, courseId, dueDate, maxScore, createdAt. Submission: id, assignmentId, userId, content (talabaning javob matni), grade (0-100, null — hali baholanmagan), feedback (o'qituvchi izohi, null bo'lishi mumkin), submittedAt, gradedAt. Talaba topshiriq yuboradi → o'qituvchi ko'radi → baho va izoh kiritadi → talabaga bildirishnoma yuboriladi. Bu butun baholash jarayoni tranzaksional tarzda amalga oshiriladi."),
  p("Notification modeli foydalanuvchilarga yuborilgan bildirishnomalarni saqlaydi: id, userId, type (info/success/warning/error), title, message, read (o'qilgan/o'qilmagan, default false), createdAt. Achievement modeli barcha mavjud nishonlarni tavsiflaydi: id, name, description, icon, condition (qanday shart bajarilganda beriladi). UserAchievement junction table: userId, achievementId, earnedAt. ActivityLog audit maqsadida barcha muhim harakatlarni saqlaydi: userId, action (lesson.create, quiz.generate va h.k.), details (JSON), createdAt."),
  p("XP va daraja tizimining algoritmi backend'da quyidagicha ishlaydi. Dars tugatilganda: newXP = user.xp + lesson.xpReward. Daraja chegaralari massivi: [0, 100, 250, 500, 900, 1400, 2000, 2800, 3800, 5000, 7000]. Yangi daraja: massivning oxiridan boshlab, newXP shu qiymatdan katta yoki teng bo'lgan birinchi indeks + 1. Masalan: 300 XP — indeks 2 (250 <= 300 < 500) → 3-daraja. User.xp va User.level atomik tarzda yangilanadi, keyin enrollment.progress qayta hisoblanadi. Bu butun jarayon bitta async funksiyada amalga oshiriladi."),
  p("Ma'lumotlar bazasini optimallashtirish — bu ishning muhim qismi. Katta so'rovlarda N+1 muammosi — eng keng tarqalgan ishlash muammolaridan biri. N+1 muammo — bir asosiy so'rov uchun N ta qo'shimcha so'rov yaratilishi. Prisma'da bu muammoning yechimi include va select direktivalari. Masalan, GET /api/courses endpoint'ida courses bilan birga instructor, enrollments._count va lessons._count ham bitta so'rovda olinadi — bu N ta qo'shimcha so'rovni oldini oladi. Bundan tashqari, ko'p qo'llaniladigan filtrlash operatsiyalari uchun @@index belgilangan."),
  p("Ma'lumotlar bazasida ma'lumotlarni saqlashning turli strategiyalari mavjud. Normalizatsiya (Normalization) — ma'lumotlarni takrorlanishini kamaytirish uchun ma'lumotlarni bir nechta jadvallarga bo'lib saqlash. 1NF, 2NF, 3NF — normalizatsiya darajalari. «EduCode»ning Prisma schema'si 3NF normallashtirish darajasiga mos — har jadvalda faqat unga tegishli ma'lumotlar saqlanadi, takrorlanish minimal. Ammo ba'zi hollarda denormalizatsiya (normalizatsiyani qaytarish) zarur bo'ladi — masalan, Enrollment jadvalida completedLessons qiymatini hisoblash o'rniga to'g'ridan-to'g'ri saqlash — bu so'rovlar tezligini sezilarli oshiradi."),
  p("Tranzaksiyalar (Transactions) ma'lumotlar yaxlitligini ta'minlovchi mexanizm. ACID xossalari: Atomicity (hamma yoki hech narsa), Consistency (ma'lumotlar har doim yaxlit holda), Isolation (parallel tranzaksiyalar bir-biriga ta'sir qilmaydi), Durability (commit bo'lgan o'zgarishlar doimiy). «EduCode»da dars tugallanishi jarayonida tranzaksiya muhim: LessonProgress yangilash, User.xp oshirish va Enrollment.progress yangilash — agar bitta amal muvaffaqiyatsiz bo'lsa, barcha amallar bekor qilinishi kerak. Prisma tranzaksiyalarni prisma.$transaction() API orqali qo'llab-quvvatlaydi."),
  p("Seed ma'lumotlari (demo data) ishlab chiqish va testlash uchun muhim. «EduCode» platformasining prisma/seed.ts faylida quyidagi demo ma'lumotlar yaratiladi: 12 ta foydalanuvchi (7 talaba, 1 o'qituvchi, 1 admin, 3 qo'shimcha), 6 ta kurs (Python, Web, SQL, Tarmoqlar, Algoritmlar, Kiberxavfsizlik), 36 ta dars (31 video, 5 quiz), 7 ta enrollment, 5 ta topshiriq, 3 ta submission, 8 ta nishon. Seed faylini bajarish uchun npx prisma db seed buyrug'i ishlatiladi. Bu buyruq loyiha birinchi marta o'rnatilganda yoki test muhiti tozalanganida ishga tushiriladi."),
  p("Xulosa qilib aytganda, «EduCode» platformasining ma'lumotlar bazasi modeli va biznes-logika qatlamlari platformaning funksional talablarini to'liq qondiradi. Prisma ORM'ning Type-safe API va avtomatik SQL injection himoyasi tizim xavfsizligini ta'minlaydi. N+1 muammosining oldini olish, tranzaksiyalar va indekslar tizimning yuqori samaradorligini kafolatlaydi. Seed ma'lumotlari tizimni tez test qilish va demonstratsiya imkonini beradi."),
  br(),
]

// ════════════════════════════════════════════════════════════
// BOB 3
// ════════════════════════════════════════════════════════════
const bob3 = [
  h1("III BOB. PLATFORMANI ISHLAB CHIQISH, SINASH VA NATIJALAR"),
  e(),
  h2("3.1. Asosiy modullarni amalga oshirish va kod arxitekturasi"),
  e(),
  p("«EduCode» platformasini ishlab chiqish jarayoni Agile metodologiyasiga asoslanib, bir haftali sprintlar ketma-ketligi sifatida tashkil etildi. Har sprint boshida Sprint Planning o'tkazildi — bajarilishi kerak bo'lgan vazifalar prioritizatsiya qilindi. Sprint oxirida Sprint Review — yaratilgan funksiyalar demo qilindi. Bu yondashuv har haftada aniqlashtirilgan maqsad va ko'rinadigan natijani ta'minladi. Jami 6 sprint davomida barcha asosiy funksiyalar amalga oshirildi."),
  p("Autentifikatsiya moduli routes/auth.ts faylida amalga oshirildi. POST /api/auth/register endpoint'i: name, email, password, role ma'lumotlarini qabul qiladi; email formatini va parol uzunligini validatsiya qiladi; prisma.user.findUnique orqali email allaqachon ro'yxatda borligini tekshiradi; bcrypt.hash(password, 8) bilan parolni xeshlaydi; prisma.user.create bilan yangi foydalanuvchi yaratadi; JWT token imzolaydi va qaytaradi. POST /api/auth/login endpoint'i: email bo'yicha foydalanuvchini topadi; bcrypt.compare() bilan parolni solishtiradi; expectedRole mos kelishini tekshiradi; token qaytaradi."),
  p("Kurslar moduli routes/courses.ts faylida amalga oshirilgan. GET /api/courses endpoint'i barcha isPublished:true kurslarni instructor ma'lumotlari va yozilganlar soni bilan birga qaytaradi. Prisma include va _count direktivlari N+1 muammosini oldini oladi. GET /api/courses/mine endpoint'i faqat joriy foydalanuvchi enrollment'lari bo'lgan kurslarni qaytaradi — bu talabaning «mening kurslarim» sahifasi uchun ishlatiladi. GET /api/courses/:id endpoint'i kurs, barcha darslar (order bo'yicha), va joriy foydalanuvchining progress ma'lumotlari bilan birga qaytaradi."),
  p("Darslar moduli routes/lessons.ts faylida amalga oshirilgan. POST /api/lessons endpoint'i: courseId, title, type majburiy maydonlari; course mavjudligi va o'qituvchi huquqini tekshiradi; oxirgi darsning order qiymatiga +1 qo'shib yangi tartib raqamini belgilaydi; kurs umumiy davomiyligini (duration) yangilaydi. PATCH /api/lessons/:id: allowed maydonlar ro'yxatidan faqat kelgan maydonlarni yangilaydi — bu partial update ta'minlaydi. POST /api/lessons/:id/complete: LessonProgress.upsert, User.xp va level yangilash, Enrollment.progress yangilash ketma-ket bajariladi."),
  p("OpenAI integratsiyasi texnik jihatdan eng murakkab qism hisoblanadi. openai npm paketi v4 versiyasi o'rnatildi. OpenAI client instansiyasi process.env.OPENAI_API_KEY bilan yaratildi. extractTextFromDataUrl(dataUrl) asinxron funksiyasi base64 data URL dan matn chiqaradi: header qismidan MIME type aniqlanadi (application/pdf yoki application/vnd.openxmlformats); buffer yaratiladi; PDF uchun pdf-parse, DOCX uchun mammoth.extractRawText() chaqiriladi; matn 6000 belgi bilan cheklanadi (token tejash uchun)."),
  p("Quiz generatsiyasining OpenAI prompt'i ehtiyotkorlik bilan yozilgan. Tizim prompt'ining asosiy ko'rsatmalari: manba matnning tilini avtomatik aniqla (inglizcha, ruscha, o'zbekcha); barcha savollarni VA javob variantlarini aynan o'sha tilda yoz; 5 ta test savoli yarat, har birida 4 ta variant; faqat bitta to'g'ri javob; faqat JSON massiv qaytir — markdown, tushuntirish, kod blok yo'q. JSON format: [{id, q, options:[A,B,C,D], correct:0}]. correct — 0-based indeks. Javob parse qilinib, lesson.content'ga JSON sifatida saqlanadi."),
  p("Student app'dagi kurs sahifasi (courses/[id]/page.tsx) platformaning eng murakkab UI komponentidir. Komponent bir nechta useState va useEffect'lar orqali boshqariladi: activeLesson — joriy tanlangan dars; quizQuestions, quizLoading, quizError — quiz holati; showXPModal — XP modal ko'rsatish. useEffect activeLesson o'zgarganda quiz'ni avtomatik yuklaydi: avval api.getQuiz() (kesh), bo'lmasa api.generateQuiz() (AI). Video player YouTube IFrame API asosida qurilgan, custom kontroller bilan."),
  p("O'qituvchi panelida kurs yaratish 3 bosqichli wizard tarzida amalga oshirilgan. step (1/2/3) state bilan boshqariladi. Birinchi qadam: kurs nomi, tavsif, kategoriya, qiyinlik. Ikkinchi qadam: darslar qo'shish (dinamik ro'yxat, har dars uchun {title, type, duration, xpReward, videoUrl}). Uchinchi qadam: har bir dars uchun resurs yuklash — FileReader.readAsDataURL() bilan fayl base64'ga o'giriladi. Wizard yakunida api.createCourse() va api.createLesson() chaqiriladi. Validatsiya har bosqichda amalga oshiriladi."),
  p("Admin panel tizimning barcha aspektlarini boshqarish imkonini beradi. /users sahifasida foydalanuvchilar jadvali: qidirish (debounced — har belgi kiritganda API chaqirilmaydi, 300ms kechikish bilan), rol bo'yicha filtrlash, yangi foydalanuvchi qo'shish modali, tahrirlash va o'chirish. /system sahifasida server holati real vaqtda ko'rsatiladi: uptime, CPU va RAM ishlatilishi, DB ulanish holati. /logs sahifasida barcha ActivityLog yozuvlari vaqt tartibida ko'rsatiladi, har yozuv uchun foydalanuvchi, harakat turi va qo'shimcha ma'lumotlar."),
  p("Kod sifatini ta'minlash uchun bir necha amaliyot qo'llanildi: ESLint — JavaScript/TypeScript kod sifat tekshiruvi, o'rnatilgan qoidalar to'plami; Prettier — avtomatik kod formatlash (bo'shliq, vergul, tirnoq uslubi); TypeScript strict mode — eng qattiq tip tekshiruvi; meaningful naming — o'zgaruvchi va funksiya nomlaridan ko'rinib turadi nima qiladi; ko'mentarlar faqat zarur holatlarda — nima qilayotganini emas, nima uchun qilayotganini tushuntiradi."),
  p("Git workflow quyidagicha tashkil etildi: main branch — ishlab chiqilgan va test qilingan kod; har bir yangi xususiyat uchun feature branch; PR (Pull Request) orqali main'ga merge; commit xabarlari konventsional format: feat: (yangi xususiyat), fix: (xato tuzatish), refactor: (qayta yozish), docs: (hujjat), chore: (texnik ish). GitHub Actions CI pipeline har push'da TypeScript tiplarini tekshiradi va build muvaffaqiyatini tasdiqlaydi. Render va Vercel GitHub'ga ulangan — main'ga merge'da avtomatik deploy amalga oshadi."),
  p("Dependency management (bog'liqliklarni boshqarish) har qanday loyihada muhim masala. npm (Node Package Manager) «EduCode»da barcha paketlarni boshqarish uchun ishlatiladi. package.json faylida dependencies (ishlab chiqishda va production'da zarur) va devDependencies (faqat ishlab chiqishda zarur) alohida ko'rsatilgan. package-lock.json fayli barcha bog'liqliklarning aniq versiyalarini qayd etadi — bu turli muhitlarda (local, CI, production) bir xil paket versiyalari o'rnatilishini kafolatlaydi. Semantic versioning (semver) — major.minor.patch format — paket versiyalarini tushunish va yangilashni tartibga soladi."),
  p("Build process (qurish jarayoni) TypeScript ilovani production'ga tayyorlashning muhim bosqichi. Backend uchun: tsc (TypeScript compiler) TypeScript kodni JavaScript'ga o'giradi, dist/ papkasiga chiqaradi; npm run build buyrug'i ham Prisma generate'ni bajaradi — Prisma Client yangilanadi. Frontend uchun Next.js build jarayoni: TypeScript tekshiruvi, React komponentlarini optimallashtirish, kodni bo'laklarga bo'lish (code splitting), statik fayllarni CDN uchun optimallashtirish. next build buyrug'i .next/ papkasida optimallashtirilgan build yaratadi."),
  p("«EduCode» platformasida maxsus e'tibor qaratilgan muhim kod patterнlari quyidagilardan iborat. Optimistic UI updates — foydalanuvchi harakat qilganda UI darhol yangilanadi, server javobi kutilmaydi; agar server xato qaytarsa, qaytarib tiklanadi. Bu UX'ni sezilarli yaxshilaydi. Debouncing — foydalanuvchi qidirish maydoniga yozayotganda har belgi kiritishda API chaqirilmaydi, 300ms kechikish bilan — bu server yukini kamaytiradi. Lazy loading — katta komponentlar va sahifalar faqat zarur bo'lganda yuklanadi — dastlabki yuklash tezligini oshiradi."),
  e(),
  h2("3.2. Platformaning funksional imkoniyatlari va foydalanish algoritmlari"),
  e(),
  p("«EduCode» platformasining asosiy funksiyalari foydalanuvchi roliga qarab farqlanadi. Talaba uchun asosiy ish oqimi (user flow) quyidagicha: /login yoki /register sahifasida kirish → /dashboard'da shaxsiy statistika (joriy XP, daraja, tugallangan kurslar, oxirgi faollik) → /courses'da kurslar katalogi, kategoriya va qiyinlik bo'yicha filtrlash → Kursga yozilish → /courses/[id] sahifasida darslarni bosqichma-bosqich o'tish → Quiz topshirish → Topshiriqlarni bajarish → /portfolio'da yutuqlar va sertifikatlarni ko'rish."),
  p("Kurs sahifasi (/courses/[id]) talaba uchun asosiy ta'lim muhiti hisoblanadi. Sahifaning chap tomonida darslar ro'yxati joylashgan — har bir dars ikona (video, quiz, yoki kod belgisi), nomi, davomiyligi, XP miqdori va holati (tugallangan yashil belgi bilan, joriy sariq ramka bilan, lock — keyingi darsga o'tish uchun avvalgisini tugatish kerak) bilan ko'rsatiladi. O'ng tomonida kontent maydoni — video darslar uchun YouTube embed player, quiz darslar uchun savollar, amaliy darslar uchun kod muhiti."),
  p("AI Quiz generatsiyasi foydalanuvchi nuqtai nazaridan quyidagicha ko'rinadi: Talaba dars sahifasida «Quiz boshlash» tugmasini bosadi; Agar keshda savollar bor bo'lsa, ular 0.5 soniyadan so'ng ko'rsatiladi; Aks holda «AI savollar tayyorlamoqda...» animatsiyasi ko'rsatiladi (Brain ikonchasi va pulsatsiya animatsiyasi); Backend resurs faylidan matn chiqaradi, OpenAI'ga yuboradi (3-8 soniya), savollarni parse qiladi va klientga qaytaradi; Savollar ekranda paydo bo'ladi — «AI tomonidan tuzildi» belgisi bilan. Talaba savolga javob berganda, rang-barang indikator ko'rsatiladi (yashil — to'g'ri, qizil — noto'g'ri)."),
  p("Quiz natijasi hisoblanishi: to'g'ri javoblar soni / jami savollar × 100 foiz. 70% dan yuqori natija — muvaffaqiyatli o'tish (yashil rang, «Tabriklaymiz!» xabari, XP ball berilgan). 70% dan past — «Qayta urinib ko'ring» tugmasi bilan. Natija ko'rsatilganda har bir savolga qaytib to'g'ri javobni ko'rish imkoniyati beriladi. Bu Immediate Feedback tamoyilini amalga oshiradi — talaba qaysi savollarda xato qilganini darhol bilib oladi va o'rganadi."),
  p("O'qituvchi uchun ish oqimi: Kirish (teacher akkaunt) → /dashboard'da KPI paneli (jami talabalar, faol kurslar, o'rtacha baho, oxirgi 7 kundagi faollik grafigi) → /courses'da o'z kurslar ro'yxati → Kurs tanlash → Darslarni boshqarish (qo'shish, tahrirlash, resurs yuklash, o'chirish) → /assignments'da talabalar yuborgan javoblar → Baho va izoh kiritish → /students'da barcha talabalar progress va at-risk ko'rsatkich → /analytics'da batafsil grafik tahlil."),
  p("Analitika moduli (apps/teacher/src/app/(app)/analytics/page.tsx) o'qituvchi uchun muhim qaror qabul qilish vositasi hisoblanadi. Haftalik faollik grafigi (LineChart) — o'tgan 7 kundagi darslar tugallanishi va login'lar. Qiyinlik darajasi taqsimoti (PieChart) — Boshlang'ich/O'rta/Yuqori nisbati. Kurslar bo'yicha progress (BarChart) — har kursda o'rtacha talaba progress foizi. AI tavsiyalari (api.aiSuggestions()) — backend talabalar ma'lumotlari asosida zaif tomonlarni aniqlab, o'qituvchiga tavsiyalar beradi."),
  p("Playground (interaktiv kod muhiti) /playground sahifasida joylashgan. Til tanlash (Python, JavaScript, SQL) → Kod muharriri (sintaksisni rang-barang ko'rsatish — Prism.js orqali) → «Ishga tushirish» tugmasi → Natija oynasi (stdout, stderr, bajarilish vaqti, exit code). Kod POST /api/code/run orqali backendga yuboriladi. Backend'da Node.js eval() (JavaScript uchun) va child_process.exec() (Python uchun) orqali sandboxed muhitda bajariladi. Xavfsizlik uchun bajarilish vaqti 5 soniya bilan cheklanib, zararli kod imkoniyatlari minimallashtirilgan."),
  p("Portfolio sahifasi (/portfolio) talabaning barcha ta'lim yutuqlarini bir joyda ko'rsatadi. Sertifikatlar bo'limi — 100% progress bilan tugallangan kurslar kartochkasi (kurs nomi, tugallangan sana, o'qituvchi ismi). Nishonlar bo'limi — olgan va hali olinmagan nishonlar (olganlar yorqin, olinmaganlar kulrang). XP tarixi grafigi (LineChart) — so'nggi 7 haftadagi XP dinamikasi. Daraja progress (ProgressBar) — joriy darajadan keyingi darajagacha qolgan XP va foiz ko'rsatiladi. Streak — ketma-ket faollik kunlari soni."),
  p("AI Chat yordamchi (/ai sahifasi) talabalar uchun 24/7 ko'mak beradi. Foydalanuvchi savolini yozadi → POST /api/ai/chat orqali backendga yuboriladi → OpenAI API orqali javob olinadi → Ekranda ko'rsatiladi. Suhbat tarixi sahifada saqlanadi (sessionStorage). AI dasturlash savollari, xatoliklarni tushuntirish, kurs tanlash bo'yicha maslahat va umumiy AKT savollari bo'yicha yordam beradi. Chat interfeysi zamonaviy messenjer uslubida — foydalanuvchi va AI xabarlari alohida pufakchalar bilan ko'rsatiladi."),
  p("Ro'yxatdan o'tish jarayoni talaba uchun quyidagicha kechadi: /register sahifasida ism, email, parol kiritiladi; frontend validatsiya (parol kamida 4 belgi, email format) o'tkaziladi; POST /api/auth/register so'rovi yuboriladi; muvaffaqiyatli bo'lsa token localStorage'ga saqlanadi va /dashboard'ga yo'naltiriladi. Kirish jarayoni (/login): email va parol kiritiladi; POST /api/auth/login; expectedRole: 'student' yuboriladi — bu boshqa roldagi foydalanuvchining student app'ga kirishini oldini oladi. Token olindi — localStorage'ga saqlanadi, Zustand store yangilanadi, /dashboard'ga o'tish."),
  p("Bildirishnomalar tizimi quyidagicha ishlaydi: Tizim bildirishnomasi yaratish uchun createNotification() yordamchi funksiyasi mavjud (routes/misc.ts). Triggerlar: kursga yozilganda o'qituvchiga; topshiriq baholanganda talabaga; yangi dars qo'shilganda yozilgan talabalarga. Frontend header'ida qo'ng'iroq belgisi — o'qilmagan bildirishnomalar soni badge'da ko'rsatiladi. Bosish bilan dropdown ro'yxat ochiladi — har bildirishnoma sarlavha, matn, vaqt va holati bilan. «Barchasini o'qilgan deb belgilash» tugmasi."),
  e(),
  h2("3.3. Tizimni testlash, samaradorlikni baholash va tahlil"),
  e(),
  p("Dasturiy ta'minotni testlash jarayoni uch asosiy qatlamda amalga oshirildi. Birlik testlash (Unit Testing) — alohida funksiya va komponentlarni tekshirish. Integratsion testlash (Integration Testing) — bir necha komponentlarning birgalikda ishlashini tekshirish. Qo'lda testlash (Manual Testing) — foydalanuvchi nuqtai nazaridan to'liq ish oqimlarini sinab ko'rish. Vaqt cheklovi sababli Jest va React Testing Library bilan avtomatlashtirilgan test suite to'liq yozilmadi, ammo asosiy funksiyalar Postman va brauzer devtools orqali sinchiklab tekshirildi."),
  p("Autentifikatsiya moduli testlash natijalari quyidagilarni ko'rsatdi: to'g'ri ma'lumotlar bilan login — 200 OK, token qaytarildi, 183ms; noto'g'ri parol — 401 Unauthorized, «Parol noto'g'ri» xabari, 62ms (bcrypt hashing tezligi); mavjud bo'lmagan email — 401 Unauthorized, 45ms; student app'dan teacher akkaunt bilan kirish — 403 Forbidden, «Bu app faqat student uchun», 68ms; muddati o'tgan token bilan so'rov — 401 Unauthorized, «Token muddati o'tgan»; token'siz himoyalangan endpoint — 401 Unauthorized, 12ms."),
  p("Kurslar va darslar moduli testlash natijalari: teacher tomonidan kurs yaratish — 201 Created, yangi kurs ID qaytarildi, 245ms; student tomonidan kurs yaratishga urinish — 403 Forbidden; kursga yozilish — 200 OK, enrollment yaratildi; bir kursga ikki marta yozilish — 400 Bad Request, «Allaqachon yozilgansiz»; darsni tugatish — 200 OK, XP ballari qaytarildi, enrollment progress yangilandi, 312ms; tugallangan darsni qayta tugatish — 200 OK, alreadyCompleted: true qaytarildi, XP ikki marta berilmadi."),
  p("Quiz generatsiyasi testlash natijalari: inglizcha PDF material bilan — inglizcha savollar generatsiya qilindi (model to'g'ri til aniqladi); ruscha Word material — ruscha savollar; o'zbekcha matn — o'zbekcha savollar; ikkinchi marta so'rash — keshdan qaytarildi, OpenAI API chaqirilmadi (0.3 soniya vs 4.2 soniya); material yuklanmagan dars — 400 Bad Request, «Bu kurs uchun hali hech qanday material yuklanmagan»; OpenAI API kaliti yo'q — 503 Service Unavailable; generatsiyalangan savollar pedagogik jihatdan to'g'ri va tushunarli baholandi."),
  p("Ishlash samaradorligi (Performance) o'lchovi quyidagi natijalarni ko'rsatdi. Backend API javob vaqti (o'rtacha, Render'dagi joylashtirishda): GET /api/courses — 178ms; GET /api/courses/:id — 224ms; POST /api/auth/login — 348ms (bcrypt hashing); POST /api/lessons/:id/complete — 267ms; GET /api/analytics/weekly — 195ms. Frontend sahifalar yuklanish vaqti (Chrome DevTools, Vercel CDN): /dashboard — 1.1 soniya (First Contentful Paint); /courses — 0.95 soniya; /courses/[id] — 1.4 soniya; Lighthouse ishlash bali: 87/100."),
  p("Xavfsizlik testlash natijalari: SQL injection urinishi (Prisma ORM himoyasi) — barcha urinishlar bloklandi, UNION-based, error-based va blind SQL injection hech biri muvaffaqiyatli bo'lmadi; XSS urinishi (React escaping) — <script>alert(1)</script> matn sifatida ko'rsatildi, bajarilmadi; CSRF urinishi (CORS whitelist) — ruxsatsiz domendan kelgan so'rovlar bloklandi; IDOR (Insecure Direct Object Reference) — boshqa foydalanuvchi ID bilan so'rov yuborilganda 403 qaytdi; brute force login — 100 urinishda ham bloklanmadi (rate limiting hali qo'shilmagan — kelajakdagi takomillashtirish)."),
  p("Foydalanuvchilar tomonidan testlash (User Acceptance Testing — UAT) uchun TATU dasturiy injiniring kafedrasi talabalari bilan fokus-guruh o'tkazildi. 15 nafar talaba va 3 nafar o'qituvchi platformani sinab ko'rib fikr bildirdi. Fikrlar maxsus shakl orqali yig'ildi: har funksiya 1-5 balli tizimda baholandi va erkin sharhlar yozildi. Natijalar: foydalanuvchi interfeysi qulay (4.2/5); quiz tizimi foydali (4.4/5); kod muhiti yaxshi, ko'proq til kerak (3.8/5); bildirishnomalar tizimi foydali (4.1/5); umumiy taassurot ijobiy (4.3/5)."),
  p("Talabalarning eng ko'p tilgan xohishlari: mobil ilova (iOS/Android); o'zbekcha kontent ko'proq bo'lishi; ko'proq dasturlash tillari (C++, Java, Go); jonli dars (real-time classroom); talabalar o'rtasida muloqot (forum yoki chat). O'qituvchilarning takliflari: toplu bildirishnoma yuborish imkoniyati; kurs statistikasini Excel'ga eksport qilish; video darslarni to'g'ridan-to'g'ri platformaga yuklash imkoniyati."),
  p("Loyihaning texnik ko'rsatkichlari va statistikasi: jami kod satrlari — 9,200+ (backend: 2,900, frontend to'rtta app: 6,300+); API endpointlari soni — 35+; Ma'lumotlar bazasi modellari — 11; GitHub commitlar soni — 55+; Vercel deploy'lar — 4 ta mustaqil loyiha; Render deploy — 1 ta backend. Demo ma'lumotlar: 12 foydalanuvchi (7 talaba, 1 o'qituvchi, 1 admin, 3 qo'shimcha), 6 kurs, 36 dars (31 video, 5 quiz), 8 nishon, 5 topshiriq, 37 ta adabiyot."),
  p("Raqamlar va samaradorlik ko'rsatkichlari: UAT'da ishtirok etgan talabalarning 80% ikkinchi kuni ham platformaga qaytdi (Retention Rate); boshlangan darslarning 73% tugallandi (Completion Rate); quiz'larda o'rtacha 68% to'g'ri javob berildi; OpenAI quiz generatsiyasi o'rtacha 4.2 soniya davom etdi; kesh ishlagan holatlarda esa 0.3 soniya. Ushbu ko'rsatkichlar platformaning pedagogik va texnik maqsadlarga erishganligini tasdiqlaydi."),
  p("Loyihada duch kelingan qiyinchiliklar va ularning yechimlari: pdf-parse TypeScript import xatosi — import * as pdfParseModule syntax bilan hal etildi; Render'da Dockerfile yo'qligi xatosi — Root Directory backend/ ga o'rnatildi; CORS sozlamasi muammosi — Vercel URL'lari whitelist'ga qo'shildi; OpenAI API'ning ba'zida markdown formatida JSON qaytarishi — regex bilan markdown blok tozalash qo'shildi; Next.js App Router'da localStorage server-side rendering'da mavjud emasligi — typeof window !== 'undefined' tekshiruvi qo'shildi."),
  br(),
]

// ════════════════════════════════════════════════════════════
// XULOSA
// ════════════════════════════════════════════════════════════
const xulosa = [
  h1("XULOSA"),
  e(),
  p("Ushbu bitiruv malakaviy ishida AKT fanini o'qitishga mo'ljallangan «EduCode» virtual ta'lim platformasi muvaffaqiyatli ishlab chiqildi. Loyiha davomida belgilangan barcha maqsad va vazifalar hal etildi. Erishilgan asosiy natijalar quyidagilardan iborat."),
  p("Birinchidan, raqamli ta'lim va e-learning texnologiyalarining rivojlanish tarixi, hozirgi holati va xalqaro tendensiyalari o'rganildi. MOOC, Microlearning, Gamifikatsiya, Mastery Learning va Adaptiv o'qitish kabi zamonaviy pedagogik yondashuvlar tahlil qilindi va «EduCode» platformasiga tatbiq etildi. Ta'lim platformalarida axborot xavfsizligi — JWT, bcrypt, RBAC, CORS, SQL injection himoyasi masalalari nazariy va amaliy jihatdan ko'rib chiqildi."),
  p("Ikkinchidan, «EduCode» platformasining to'liq texnik arxitekturasi loyihalandi: monorepo tuzilmasi (backend + 4 frontend app), JAMStack yondashuvi, 35+ API endpoint, 11 ta Prisma modeli. Texnologiyalar tanlovi asoslanib, Next.js 14, Node.js/Express, Prisma ORM, Neon PostgreSQL, Zustand, Tailwind CSS, Recharts, OpenAI API tanlandi va muvaffaqiyatli qo'llanildi."),
  p("Uchinchidan, to'liq funksional platforma ishlab chiqildi: talaba, o'qituvchi va admin uchun alohida panellar; kurs, dars, topshiriqlarni boshqarish; XP va daraja tizimi; AI quiz generatsiyasi (PDF/Word materialdan ko'p tilli savollar); interaktiv kod muhiti; real vaqt analitika va bildirishnomalar. Platforma GitHub'da joylashtirilgan va Render (backend) hamda Vercel (frontend) da real foydalanuvchilar uchun ochiq."),
  p("To'rtinchidan, platformaning testlash natijalari barcha asosiy funksiyalarning to'g'ri ishlashini tasdiqladi. 15 talaba va 3 o'qituvchi ishtirokidagi UAT sessiyasida o'rtacha 4.3/5 baho olindi. API javob vaqtlari va sahifalar yuklanish ko'rsatkichlari belgilangan NFR talablariga mos keldi."),
  p("Loyihaning ilmiy yangiligi: O'zbekistonda birinchi marta AKT fani uchun maxsus, OpenAI integratsiyali, ko'p tilli quiz generatsiyali, Microlearning va Gamifikatsiyani birlashtirgan milliy virtual ta'lim platformasi yaratildi."),
  e(),
  pb("Kelajakdagi takomillashtirish yo'nalishlari:"),
  p("1. Xavfsizlik: express-rate-limit va helmet middleware'larini qo'shish, refresh token rotatsiyasi, 2FA adminlar uchun."),
  p("2. Real-time funksiyalar: Socket.io orqali jonli dars, real vaqt bildirishnomalar, ko'p foydalanuvchili playground."),
  p("3. Mobil ilova: React Native yoki Expo orqali iOS va Android ilovalar."),
  p("4. Ko'proq til qo'llashi: C++, Java, Go dasturlash tillarini playground'ga qo'shish."),
  p("5. To'lov tizimi: Payme, Click, Uzcard integratsiyasi va premium kurslar."),
  p("6. Sertifikatlashtirish: PDF sertifikat generatsiyasi va blockchain'da tasdiqlash."),
  p("7. Offline rejim: Progressive Web App (PWA) va Service Worker."),
  br(),
]

// ════════════════════════════════════════════════════════════
// ADABIYOTLAR
// ════════════════════════════════════════════════════════════
const adabiyotlar = [
  h1("FOYDALANILGAN ADABIYOTLAR"),
  e(),
  pb("Rasmiy hujjatlar va qonunchilik:", { para: { indent: { firstLine: 0 } } }),
  p("1. O'zbekiston Respublikasi Prezidentining 2020-yil 5-oktabrdagi PF-6079-son Farmoni «O'zbekiston Respublikasini yanada rivojlantirish bo'yicha Harakatlar strategiyasi to'g'risida». — Toshkent, 2020."),
  p("2. «Raqamli O'zbekiston — 2030» strategiyasi. O'zbekiston Respublikasi Prezidentining 2020-yil 28-apreldagi PF-5992-son Farmoni. — Toshkent, 2020."),
  p("3. O'zbekiston Respublikasining «Ta'lim to'g'risida»gi qonuni (29.08.1997 y. 464-I-son, yangi tahrirda 2020). — Toshkent."),
  p("4. O'zbekiston Respublikasining «Shaxsga doir ma'lumotlar to'g'risida»gi qonuni (2019.07.02, 547-son). — Toshkent, 2019."),
  p("5. O'zbekiston Respublikasining «Axborot texnologiyalari va axborotni himoyalash to'g'risida»gi qonuni. — Toshkent, 2003."),
  p("6. Mirziyoyev Sh.M. Yangi O'zbekiston taraqqiyot strategiyasi. — Toshkent: O'zbekiston nashriyoti, 2022. — 464 b."),
  e(),
  pb("Darsliklar va monografiyalar:", { para: { indent: { firstLine: 0 } } }),
  p("7. Anderson T., Dron J. Three generations of distance education pedagogy // International Review of Research in Open and Distributed Learning. — 2011. — Vol. 12, №3. — P. 80—97."),
  p("8. Bersin J. The Blended Learning Book: Best Practices, Proven Methodologies, and Lessons Learned. — Pfeiffer, 2004. — 352 p."),
  p("9. Bloom B.S. Learning for Mastery // Evaluation Comment. — 1968. — Vol. 1, №2. — P. 1—12."),
  p("10. Clark R.C., Mayer R.E. e-Learning and the Science of Instruction: Proven Guidelines for Consumers and Designers of Multimedia Learning. 4th ed. — Wiley, 2016. — 624 p."),
  p("11. Deterding S., Dixon D., Khaled R., Nacke L. From game design elements to gamefulness: Defining gamification // Proceedings of the 15th International Academic MindTrek Conference. — 2011. — P. 9—15."),
  p("12. Fowler M. Patterns of Enterprise Application Architecture. — Addison-Wesley, 2002. — 560 p."),
  p("13. Garrison D.R., Vaughan N.D. Blended Learning in Higher Education. — Jossey-Bass, 2008. — 272 p."),
  p("14. Hamari J., Koivisto J., Sarsa H. Does Gamification Work? — A Literature Review of Empirical Studies on Gamification // 47th Hawaii International Conference on System Sciences. — 2014."),
  p("15. Hattie J., Timperley H. The Power of Feedback // Review of Educational Research. — 2007. — Vol. 77, №1. — P. 81—112."),
  p("16. Hrastinski S. Asynchronous and synchronous e-learning // EDUCAUSE Quarterly. — 2008. — №4. — P. 51—55."),
  p("17. Kapp K.M., Defelice R.A. Microlearning: Short and Sweet. — ATD Press, 2019. — 168 p."),
  p("18. Koller D., Ng A., Do C., Chen Z. Retention and Intention in Massive Open Online Courses // EDUCAUSE Review. — 2013."),
  p("19. Mayer R.E. Multimedia Learning. 2nd ed. — Cambridge University Press, 2009. — 320 p."),
  p("20. Means B., Toyama Y., Murphy R., Bakia M. Evaluation of Evidence-Based Practices in Online Learning. — U.S. Department of Education, 2013."),
  p("21. Siemens G. Learning Analytics: The Emergence of a Discipline // American Behavioral Scientist. — 2013. — Vol. 57, №10. — P. 1380—1400."),
  p("22. Vygotsky L.S. Mind in Society: The Development of Higher Psychological Processes. — Harvard University Press, 1978. — 159 p."),
  e(),
  pb("Dasturlash va texnologiyalar:", { para: { indent: { firstLine: 0 } } }),
  p("23. Abramov A., Kovalyov V. Node.js. Putevoditel' razrabotchika. — SPb.: Piter, 2021. — 416 s."),
  p("24. Banks A., Porcello E. Learning React. 2nd ed. — O'Reilly, 2020. — 310 p."),
  p("25. Brown E. Web Development with Node and Express. 2nd ed. — O'Reilly, 2019. — 424 p."),
  p("26. Cherny B. Programming TypeScript. — O'Reilly, 2019. — 352 p."),
  p("27. Grigorik I. High Performance Browser Networking. — O'Reilly, 2013. — 408 p."),
  p("28. Hunt A., Thomas D. The Pragmatic Programmer: 20th Anniversary Edition. — Addison-Wesley, 2019. — 352 p."),
  p("29. Martin R.C. Clean Code: A Handbook of Agile Software Craftsmanship. — Prentice Hall, 2008. — 431 p."),
  p("30. Shklar L., Rosen R. Web Application Architecture: Principles, Protocols and Practices. 2nd ed. — Wiley, 2009. — 400 p."),
  p("31. Wieruch R. The Road to React. — Self-published, 2022. — 326 p."),
  e(),
  pb("Internet manbalari:", { para: { indent: { firstLine: 0 } } }),
  p("32. Next.js Documentation. App Router. — https://nextjs.org/docs (murojaat: 15.04.2026)."),
  p("33. Prisma Documentation. Getting Started. — https://prisma.io/docs (murojaat: 18.04.2026)."),
  p("34. OpenAI API Reference. Chat Completions. — https://platform.openai.com/docs (murojaat: 20.04.2026)."),
  p("35. Tailwind CSS Documentation. — https://tailwindcss.com/docs (murojaat: 10.04.2026)."),
  p("36. Neon PostgreSQL Documentation. — https://neon.tech/docs (murojaat: 12.04.2026)."),
  p("37. Vercel Documentation. Next.js Deployment. — https://vercel.com/docs (murojaat: 22.04.2026)."),
  p("38. Render Documentation. Web Services. — https://render.com/docs (murojaat: 22.04.2026)."),
  p("39. OWASP Top 10. — https://owasp.org/www-project-top-ten/ (murojaat: 05.04.2026)."),
  p("40. JWT.io Introduction. — https://jwt.io/introduction (murojaat: 08.04.2026)."),
  p("41. Zustand Documentation. — https://zustand-demo.pmnd.rs/ (murojaat: 11.04.2026)."),
  br(),
]

// ════════════════════════════════════════════════════════════
// ILOVALAR
// ════════════════════════════════════════════════════════════
const ilovalar = [
  h1("ILOVALAR"),
  e(),
  h2("1-ilova. \"EduCode\" platformasining umumiy arxitektura diagrammasi"),
  e(),
  p("Platforma to'rtta mustaqil komponentdan iborat: 1) Backend server (Node.js 20/Express 4/TypeScript, Render'da joylashtirilgan) — barcha biznes-mantiq, JWT autentifikatsiya, Prisma ORM orqali PostgreSQL bilan muloqot, va OpenAI API integratsiyasi. 2) Talaba ilovasi (Next.js 14, Vercel #1) — darslar, quiz, playground, portfolio. 3) O'qituvchi ilovasi (Next.js 14, Vercel #2) — kurs yaratish, baholash, analitika. 4) Admin ilovasi (Next.js 14, Vercel #3) — tizim boshqaruvi, foydalanuvchilar, statistika. 5) Landing sahifasi (Next.js 14, Vercel #4) — rol tanlash kirish sahifasi."),
  p("Barcha frontend ilovalari bitta backend API server bilan HTTPS orqali gaplashadi. Neon PostgreSQL bulutli ma'lumotlar bazasi Prisma ORM orqali backend'ga ulangan. OpenAI GPT-4o-mini API quiz generatsiyasi uchun backend tomonidan chaqiriladi. GitHub repozitoriy Render va Vercel bilan ulangan — main branch'ga har push'da avtomatik CI/CD pipeline ishlaydi."),
  e(),
  h2("2-ilova. Prisma Schema — asosiy modellar"),
  e(),
  p("model User { id String @id @default(cuid()); name String; email String @unique; password String; role String @default(\"student\"); xp Int @default(0); level Int @default(1); streak Int @default(0); lastActive DateTime?; createdAt DateTime @default(now()); courses Course[] @relation(\"Instructor\"); enrollments Enrollment[]; progress LessonProgress[]; submissions Submission[]; notifications Notification[]; achievements UserAchievement[]; logs ActivityLog[]; @@index([role]); }"),
  p("model Course { id String @id @default(cuid()); title String; description String; category String; level String; duration String @default(\"1 soat\"); thumbnail String?; instructorId String; isPublished Boolean @default(true); createdAt DateTime @default(now()); instructor User @relation(\"Instructor\", fields: [instructorId], references: [id]); lessons Lesson[]; enrollments Enrollment[]; assignments Assignment[]; @@index([instructorId]); }"),
  p("model Lesson { id String @id @default(cuid()); courseId String; title String; type String; duration String; xpReward Int @default(20); order Int @default(0); content String?; videoUrl String?; resourceUrl String?; resourceName String?; resourceType String?; course Course @relation(fields: [courseId], references: [id], onDelete: Cascade); progress LessonProgress[]; @@index([courseId]); }"),
  p("model Enrollment { id String @id @default(cuid()); userId String; courseId String; progress Int @default(0); completedLessons Int @default(0); enrolledAt DateTime @default(now()); user User @relation(fields: [userId], references: [id]); course Course @relation(fields: [courseId], references: [id]); @@unique([userId, courseId]); }"),
  p("model LessonProgress { id String @id @default(cuid()); userId String; lessonId String; completed Boolean @default(false); completedAt DateTime?; user User @relation(fields: [userId], references: [id]); lesson Lesson @relation(fields: [lessonId], references: [id]); @@unique([userId, lessonId]); }"),
  e(),
  h2("3-ilova. API endpointlar to'liq ro'yxati"),
  e(),
  p("POST   /api/auth/login                          — Tizimga kirish (JWT qaytaradi)"),
  p("POST   /api/auth/register                       — Yangi foydalanuvchi ro'yxatdan o'tkazish"),
  p("GET    /api/auth/me                             — Joriy foydalanuvchi ma'lumotlari"),
  p("POST   /api/auth/logout                         — Chiqish"),
  p("GET    /api/courses                             — Barcha nashr qilingan kurslar"),
  p("GET    /api/courses/mine                        — Joriy foydalanuvchi yozilgan kurslar"),
  p("GET    /api/courses/:id                         — Kurs, darslar va progress"),
  p("POST   /api/courses/:id/enroll                 — Kursga yozilish"),
  p("POST   /api/courses                             — Yangi kurs yaratish (teacher/admin)"),
  p("PATCH  /api/courses/:id                         — Kursni tahrirlash"),
  p("DELETE /api/courses/:id                         — Kursni o'chirish"),
  p("POST   /api/lessons                             — Yangi dars yaratish"),
  p("PATCH  /api/lessons/:id                         — Darsni tahrirlash"),
  p("DELETE /api/lessons/:id                         — Darsni o'chirish"),
  p("POST   /api/lessons/:id/complete               — Darsni tugatish va XP olish"),
  p("POST   /api/lessons/:id/generate-quiz          — AI orqali quiz generatsiya"),
  p("GET    /api/lessons/:id/quiz                   — Keshdan quiz olish"),
  p("GET    /api/assignments/mine                   — Talaba topshiriqlari"),
  p("GET    /api/assignments/teaching               — O'qituvchi topshiriqlari"),
  p("POST   /api/assignments/:id/submit             — Topshiriq yuborish"),
  p("GET    /api/assignments/:id/submissions        — Barcha javoblar ro'yxati"),
  p("POST   /api/assignments/submissions/:id/grade — Baholash"),
  p("POST   /api/assignments                        — Yangi topshiriq yaratish"),
  p("DELETE /api/assignments/:id                    — Topshiriqni o'chirish"),
  p("GET    /api/users                              — Barcha foydalanuvchilar (admin)"),
  p("GET    /api/users/students                     — Faqat studentlar"),
  p("POST   /api/users                              — Yangi foydalanuvchi yaratish"),
  p("PATCH  /api/users/:id                          — Foydalanuvchini tahrirlash"),
  p("DELETE /api/users/:id                          — Foydalanuvchini o'chirish"),
  p("GET    /api/notifications                      — Bildirishnomalar"),
  p("POST   /api/notifications/:id/read            — O'qilgan deb belgilash"),
  p("GET    /api/achievements                       — Barcha nishonlar"),
  p("GET    /api/analytics/weekly                   — Haftalik analitika"),
  p("GET    /api/analytics/difficulty              — Qiyinlik darajasi statistikasi"),
  p("GET    /api/analytics/growth                  — Foydalanuvchilar o'sishi"),
  p("GET    /api/analytics/ai-suggestions          — AI tavsiyalari"),
  p("GET    /api/system/stats                       — Tizim statistikasi"),
  p("GET    /api/system/logs                        — Tizim jurnali"),
  p("POST   /api/ai/chat                            — AI yordamchi"),
  p("POST   /api/code/run                           — Kodni ishga tushirish"),
  p("GET    /api/health                             — Sog'liq tekshiruvi"),
  e(),
  h2("4-ilova. Demo hisoblar"),
  e(),
  p("Platforma quyidagi demo hisoblar bilan sozlangan (barcha parollar: 1234):"),
  p("Talabalar: durdona@student.uz (asosiy talaba), nilufar@edu.uz, bobur@edu.uz, shahlo@edu.uz, jasur@edu.uz, malika@edu.uz, sardor@edu.uz, zulfiya@edu.uz"),
  p("O'qituvchi: durdona@gmail.com"),
  p("Admin: durdona@admin.uz"),
  p("Kurslar: Python dasturlash asoslari, Web-dasturlash (HTML/CSS/JS), SQL va ma'lumotlar bazasi, Kompyuter tarmoqlari, Algoritmlar va ma'lumotlar tuzilmasi, Kiberxavfsizlik asoslari"),
  e(),
  h2("5-ilova. Texnologiyalar versiyalari"),
  e(),
  p("Backend: Node.js 20.x LTS, Express 4.18.x, TypeScript 5.x, Prisma 5.x, jsonwebtoken 9.x, bcryptjs 2.x, openai 4.x, pdf-parse 1.x, mammoth 1.x, morgan 1.x, cors 2.x"),
  p("Frontend: Next.js 14.x, React 18.x, TypeScript 5.x, Tailwind CSS 3.x, Zustand 4.x, Recharts 2.x, Lucide-react 0.x, docx 8.x"),
  p("Infratuzilma: Neon PostgreSQL (serverless), Render (backend hosting), Vercel (frontend hosting × 4), GitHub (version control + CI/CD), OpenAI GPT-4o-mini"),
  e(),
  h2("6-ilova. Deployment konfiguratsiyasi"),
  e(),
  p("Backend (Render): Root Directory: backend; Build Command: npm install && npm run build && npx prisma db push; Start Command: npm start; Muhit o'zgaruvchilari: DATABASE_URL (Neon pooled URL), JWT_SECRET (32+ belgi tasodifiy), CORS_ORIGINS (Vercel URL'lari vergul bilan), PORT=8080, OPENAI_API_KEY (OpenAI platform'dan)"),
  p("Frontend (Vercel): Student Root: apps/student; Teacher Root: apps/teacher; Admin Root: apps/admin; Landing Root: apps/landing. Framework Preset: Next.js (avtomatik). Build Command: next build. Muhit: NEXT_PUBLIC_API_URL=https://durdona-bmi.onrender.com"),
  e(),
  h2("7-ilova. XP va daraja tizimi"),
  e(),
  p("Daraja 1: 0 — 99 XP. Daraja 2: 100 — 249 XP. Daraja 3: 250 — 499 XP. Daraja 4: 500 — 899 XP. Daraja 5: 900 — 1399 XP. Daraja 6: 1400 — 1999 XP. Daraja 7: 2000 — 2799 XP. Daraja 8: 2800 — 3799 XP. Daraja 9: 3800 — 4999 XP. Daraja 10: 5000 — 6999 XP. Daraja 11 (Usta): 7000+ XP."),
  p("Har darsni tugatganda: 10-50 XP (darsga qarab). Quiz'ni muvaffaqiyatli tugatganda: +10 bonus XP. Haftalik streak (7 kun ketma-ket faollik): +50 XP. Birinchi kursni tugatganda: «Kelajak dasturchi» nishoni. 5 kursni tugatganda: «Bilim izlovchi» nishoni. 7 kunlik streak: «Izchil talaba» nishoni."),
  e(),
  h2("8-ilova. Loyiha GitHub repozitoriy statistikasi"),
  e(),
  p("Repozitoriy: GitHub'da joylashtirilgan. Asosiy branch: main. Jami commitlar: 55+. Eng ko'p o'zgartirilgan fayllar: backend/src/routes/lessons.ts (OpenAI integratsiya), apps/student/src/app/(app)/courses/[id]/page.tsx (kurs sahifasi), backend/prisma/schema.prisma (ma'lumotlar modeli). Yangi fayllar: backend/src/routes/lessons.ts (pdf-parse, mammoth, openai), apps/landing/ (yangi app), generate-bmi.mjs (hujjat generatori)."),
]

// ════════════════════════════════════════════════════════════
// DOCUMENT ASSEMBLY
// ════════════════════════════════════════════════════════════
const doc = new Document({
  styles: {
    default: {
      document: {
        run: { font: FONT, size: SIZE },
        paragraph: { spacing: { after: 0, ...LINE }, alignment: AlignmentType.JUSTIFIED },
      },
    },
  },
  sections: [{
    properties: {
      page: {
        size: { width: 11906, height: 16838 },
        margin: { top: 1134, right: 851, bottom: 1134, left: 1701, header: 720, footer: 720 },
      },
    },
    children: [
      ...titlePage,
      ...mundarija,
      ...kirish,
      ...bob1,
      ...bob2,
      ...bob3,
      ...xulosa,
      ...adabiyotlar,
      ...ilovalar,
    ],
  }],
})

Packer.toBuffer(doc).then(buf => {
  writeFileSync('Durdona_BMI.docx', buf)
  console.log('✓ Durdona_BMI.docx yaratildi!')
})
